.class public LX/7OH;
.super Ljava/lang/Object;


# instance fields
.field public A00:I

.field public A01:I

.field public A02:I

.field public A03:I

.field public A04:I

.field public A05:I

.field public A06:I

.field public A07:I

.field public A08:I

.field public A09:I

.field public A0A:I

.field public A0B:I

.field public A0C:I

.field public A0D:I

.field public A0E:I

.field public A0F:J

.field public A0G:LX/8CA;

.field public A0H:LX/8CA;

.field public A0I:LX/8CD;

.field public A0J:LX/8CT;

.field public A0K:LX/8CE;

.field public A0L:LX/8C8;

.field public A0M:LX/8CC;

.field public A0N:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

.field public A0O:LX/8CJ;

.field public A0P:LX/8CB;

.field public A0Q:LX/8C7;

.field public A0R:LX/8CL;

.field public A0S:LX/8CL;

.field public A0T:LX/8C9;

.field public A0U:Ljava/lang/String;

.field public A0V:Ljava/util/HashMap;

.field public A0W:Ljava/util/Map;

.field public A0X:Ljava/util/Set;

.field public A0Y:Ljava/util/Set;

.field public A0Z:Ljava/util/Set;

.field public A0a:Ljava/util/Set;

.field public A0b:Ljava/util/Set;

.field public A0c:Ljava/util/Set;

.field public A0d:Z

.field public A0e:Z

.field public A0f:Z

.field public A0g:Z

.field public A0h:Z

.field public A0i:Z

.field public A0j:Z

.field public A0k:Z

.field public A0l:Z

.field public A0m:Z

.field public A0n:Z

.field public A0o:Z


# direct methods
.method public constructor <init>()V
    .locals 7

    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    const/4 v1, 0x0

    iput-boolean v1, p0, LX/7OH;->A0n:Z

    sget-object v0, LX/8CU;->A00:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

    iput-object v0, p0, LX/7OH;->A0N:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

    const/4 v2, 0x1

    iput-boolean v1, p0, LX/7OH;->A0e:Z

    const/4 v0, 0x3

    iput v0, p0, LX/7OH;->A07:I

    const/16 v3, 0x7d0

    const-string v0, "ExoService"

    iput-object v0, p0, LX/7OH;->A0U:Ljava/lang/String;

    const/16 v6, 0xfa

    iput-boolean v2, p0, LX/7OH;->A0m:Z

    new-instance v0, LX/7Ox;

    invoke-direct {v0}, LX/7Ox;-><init>()V

    iget-boolean v2, v0, LX/7Ox;->A00:Z

    new-instance v0, LX/8CC;

    invoke-direct {v0, v2}, LX/8CC;-><init>(Z)V

    iput-object v0, p0, LX/7OH;->A0M:LX/8CC;

    const/16 v2, 0x3e8

    const/16 v5, 0x1f4

    new-instance v0, LX/8CL;

    invoke-direct {v0, v5, v3}, LX/8CL;-><init>(II)V

    iput-object v0, p0, LX/7OH;->A0R:LX/8CL;

    new-instance v0, LX/8CL;

    invoke-direct {v0, v1, v1}, LX/8CL;-><init>(II)V

    iput-object v0, p0, LX/7OH;->A0S:LX/8CL;

    new-instance v0, LX/8CJ;

    invoke-direct {v0}, LX/8CJ;-><init>()V

    iput-object v0, p0, LX/7OH;->A0O:LX/8CJ;

    new-instance v0, LX/74c;

    invoke-direct {v0}, LX/74c;-><init>()V

    new-instance v0, LX/8CE;

    invoke-direct {v0}, LX/8CE;-><init>()V

    iput-object v0, p0, LX/7OH;->A0K:LX/8CE;

    sget-object v0, LX/8CT;->A00:LX/8CT;

    iput-object v0, p0, LX/7OH;->A0J:LX/8CT;

    new-instance v0, LX/74W;

    invoke-direct {v0}, LX/74W;-><init>()V

    new-instance v0, LX/8CD;

    invoke-direct {v0}, LX/8CD;-><init>()V

    iput-object v0, p0, LX/7OH;->A0I:LX/8CD;

    new-instance v0, LX/74d;

    invoke-direct {v0}, LX/74d;-><init>()V

    new-instance v0, LX/8C8;

    invoke-direct {v0}, LX/8C8;-><init>()V

    iput-object v0, p0, LX/7OH;->A0L:LX/8C8;

    new-instance v0, LX/74f;

    invoke-direct {v0}, LX/74f;-><init>()V

    new-instance v0, LX/8C9;

    invoke-direct {v0}, LX/8C9;-><init>()V

    iput-object v0, p0, LX/7OH;->A0T:LX/8C9;

    new-instance v0, LX/8C7;

    invoke-direct {v0}, LX/8C7;-><init>()V

    iput-object v0, p0, LX/7OH;->A0Q:LX/8C7;

    new-instance v4, LX/7L0;

    invoke-direct {v4}, LX/7L0;-><init>()V

    const v0, 0x186a0

    iput v0, v4, LX/7L0;->A00:I

    iput v2, v4, LX/7L0;->A03:I

    iput v5, v4, LX/7L0;->A02:I

    iput v6, v4, LX/7L0;->A01:I

    new-instance v0, LX/8CA;

    invoke-direct {v0, v4}, LX/8CA;-><init>(LX/7L0;)V

    iput-object v0, p0, LX/7OH;->A0G:LX/8CA;

    new-instance v4, LX/7L0;

    invoke-direct {v4}, LX/7L0;-><init>()V

    iput v3, v4, LX/7L0;->A00:I

    const v0, 0x249f0

    iput v0, v4, LX/7L0;->A03:I

    const v0, 0x86470

    iput v0, v4, LX/7L0;->A02:I

    const v0, 0x1e8480

    iput v0, v4, LX/7L0;->A01:I

    new-instance v0, LX/8CA;

    invoke-direct {v0, v4}, LX/8CA;-><init>(LX/7L0;)V

    iput-object v0, p0, LX/7OH;->A0H:LX/8CA;

    iput-boolean v1, p0, LX/7OH;->A0f:Z

    iput-boolean v1, p0, LX/7OH;->A0h:Z

    const/16 v6, 0xfa0

    invoke-static {}, LX/001;->A0y()Ljava/util/HashMap;

    move-result-object v0

    iput-object v0, p0, LX/7OH;->A0V:Ljava/util/HashMap;

    const-wide/16 v4, 0x0

    iput-wide v4, p0, LX/7OH;->A0F:J

    invoke-static {}, LX/001;->A0y()Ljava/util/HashMap;

    move-result-object v0

    iput-object v0, p0, LX/7OH;->A0W:Ljava/util/Map;

    const/16 v0, 0x7530

    iput v0, p0, LX/7OH;->A04:I

    const/4 v0, -0x1

    iput v0, p0, LX/7OH;->A0D:I

    iput v6, p0, LX/7OH;->A03:I

    invoke-static {}, LX/001;->A0z()Ljava/util/HashSet;

    move-result-object v0

    iput-object v0, p0, LX/7OH;->A0a:Ljava/util/Set;

    invoke-static {}, LX/001;->A0z()Ljava/util/HashSet;

    move-result-object v0

    iput-object v0, p0, LX/7OH;->A0Z:Ljava/util/Set;

    invoke-static {}, LX/001;->A0z()Ljava/util/HashSet;

    move-result-object v0

    iput-object v0, p0, LX/7OH;->A0b:Ljava/util/Set;

    new-instance v0, LX/8CB;

    invoke-direct {v0}, LX/8CB;-><init>()V

    iput-object v0, p0, LX/7OH;->A0P:LX/8CB;

    invoke-static {}, LX/001;->A0z()Ljava/util/HashSet;

    move-result-object v0

    iput-object v0, p0, LX/7OH;->A0Y:Ljava/util/Set;

    invoke-static {}, LX/001;->A0z()Ljava/util/HashSet;

    move-result-object v0

    iput-object v0, p0, LX/7OH;->A0X:Ljava/util/Set;

    invoke-static {}, LX/001;->A0z()Ljava/util/HashSet;

    move-result-object v0

    iput-object v0, p0, LX/7OH;->A0c:Ljava/util/Set;

    const/16 v0, 0x28

    iput v0, p0, LX/7OH;->A0C:I

    iput v0, p0, LX/7OH;->A0B:I

    iput v1, p0, LX/7OH;->A08:I

    const/4 v0, -0x1

    iput v0, p0, LX/7OH;->A09:I

    iput v0, p0, LX/7OH;->A0E:I

    iput v2, p0, LX/7OH;->A06:I

    iput v3, p0, LX/7OH;->A05:I

    iput v2, p0, LX/7OH;->A00:I

    iput v2, p0, LX/7OH;->A02:I

    const v0, 0x8000

    iput v0, p0, LX/7OH;->A01:I

    iput-boolean v1, p0, LX/7OH;->A0g:Z

    iput-boolean v1, p0, LX/7OH;->A0d:Z

    iput-boolean v1, p0, LX/7OH;->A0l:Z

    const/16 v0, 0x18

    iput v0, p0, LX/7OH;->A0A:I

    iput-boolean v1, p0, LX/7OH;->A0o:Z

    return-void
.end method
