.class public LX/8CU;
.super Ljava/lang/Object;

# interfaces
.implements Ljava/io/Serializable;


# static fields
.field public static final A00:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

.field public static final A01:LX/8CU;

.field public static final serialVersionUID:J = -0xb6b8c66d093f82bL


# instance fields
.field public final abrMonitorEnabled:Z

.field public final abrSetting:LX/8CE;

.field public final adBreakEnahncedPrefetchDurationMs:I

.field public final adjustSpeedBottomThresholdMs:I

.field public final adjustSpeedTopThresholdMs:I

.field public final advanceSegmentOnNetworkErrors:J

.field public final aggressiveEdgeLatencyForLsbConfPercentile:I

.field public final aggressiveEdgeLatencyOverrideForLSB:J

.field public final allowImmediateLiveBufferTrim:Z

.field public final allowMultiPlayerFormatWarmup:Z

.field public final allowOutOfBoundsAccessForPDash:Z

.field public final allowOverridingPlayerWarmUpWatermark:Z

.field public final allowPredictiveAlignment:Z

.field public final allowRequestForSoftwareDecoder:Z

.field public final allowedExtendedMinRebuffePeriodMs:I

.field public final allowedExtendedPremiumTierRebufferPeriodMs:I

.field public final allowedExtendedRebufferPeriodMs:I

.field public final alwaysPerformContentLengthUpdateFirst:Z

.field public final alwaysPrefetchInBgDefaultPriorityThread:Z

.field public final alwaysPrefetchInIdleExecutor:Z

.field public final alwaysReuseManifestFetcher:Z

.field public final appendReconfigurationDataForDrmContentFix:Z

.field public final asyncReleaseSurfaceOnMainThread:Z

.field public final attachGrootPlayerListenerWhenUsingSurfaceControl:Z

.field public final audioBufferSize:I

.field public final audioLazyLoadSetting:LX/8C8;

.field public final audioStallCountThresholdMs:I

.field public final audioTrackInitFailedFallbackApplyThreshold:I

.field public final audioVideoSyncPeriodMs:I

.field public final autogenSettings:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

.field public final av1Dav1dEnableVpsLogging:Z

.field public final av1Dav1dUseSurfaceViewSetFix:Z

.field public final av1FlushDav1dProperly:Z

.field public final av1SetBuffersDataspace:Z

.field public final av1ThrowExceptionOnNonDav1dDecoder:Z

.field public final av1ThrowExceptionOnPictureError:Z

.field public final av1UseDav1dSynchronizationFixes:Z

.field public final av1UseMemoryCleanupFixes:Z

.field public final avoidSecondPhaseOnCell:Z

.field public final avoidServiceClassLoadOnClient:Z

.field public final bandwidthMultiplierForAggressiveEdgeLatency:F

.field public final bandwidthMultiplierToSkipPrefetchedContent:F

.field public final bgHeroServiceStatusUpdate:Z

.field public final blackscreenDetectOnce:Z

.field public final blackscreenNoSampleThresholdMs:J

.field public final blackscreenSampleIntervalMs:J

.field public final blockDRMPlaybackOnHDMI:Z

.field public final blockDRMScreenCapture:Z

.field public final blockListedHardwareDecoderMap:Ljava/util/HashMap;

.field public final broadcasterIdAllowlist:Ljava/lang/String;

.field public final bufferDecreaseTimeMs:I

.field public final bufferedCacheDataSinkSize:I

.field public final bufferedDurationBasedHttpPriorityLowerBoundMs:I

.field public final bufferedDurationBasedHttpPriorityUpperBoundMs:I

.field public final bypassGreaterThanMinRebufferWhenBeforePlay:Z

.field public final cache:LX/8CC;

.field public final callbackFirstCaughtStreamError:Z

.field public final cancelOngoingRequest:Z

.field public final cellMaxWatermarkMsConfig:LX/8CA;

.field public final changePriorityForPrefetchRequestOnPlayerStart:Z

.field public final changeThreadPriorityForPrefetch:Z

.field public final checkCachedLockedCacheSpan:Z

.field public final checkLiveSourceUri:Z

.field public final checkManifestRepresentationFormatMismatch:Z

.field public final checkPlayerStateIntervalIncreaseMs:I

.field public final checkPlayerStateMaxIntervalMs:I

.field public final checkPlayerStateMinIntervalMs:I

.field public final checkReadToEndBeforeUpdatingFinalState:Z

.field public final checkThumbnailCache:Z

.field public final chunkSourceRetryMaximum:I

.field public final cleanUpHeartbeatMessagesIfNotPlaying:Z

.field public final cleanUpHeartbeatMessagesOnPause:Z

.field public final cleanUpHeartbeatMessagesOnStall:Z

.field public final clearBufferingWhenInWarmup:Z

.field public final combineInitFirstSegment:Z

.field public final concatenatedMsPerLoadConfig:LX/8CA;

.field public final continueLoadingOnSeekbarExo2:Z

.field public final continuouslyLoadFromPreSeekLocation:Z

.field public final customizedPrefetchThreadPriority:I

.field public final customizedWABufferForPlaybackMs:I

.field public final customizedWAIndividualAllocationSize:I

.field public final customizedWARebufferMs:I

.field public final dashHighWatermarkMs:I

.field public final dashLowWatermarkMs:I

.field public final dashManifestPoolSize:I

.field public final dav1dApplyGrain:Z

.field public final dav1dMaxFrameDelay:I

.field public final dav1dThreads:I

.field public final decoderDequeueRetryTimeMs:I

.field public final decoderInitializationRetryTimeMs:I

.field public final defaultUserAgent:Ljava/lang/String;

.field public final delayWarmupRunningMs:I

.field public final depthTocheckSurfaceInvisibleParent:I

.field public final desiredBufferAcceptableErrorMs:I

.field public final disableAudioFocusInGroot:Z

.field public final disableAudioRendererOnAudioTrackInitFailed:Z

.field public final disableCapBufferSizeLocalProgressive:Z

.field public final disableIsCachedApi:Z

.field public final disableLatencyManagerOnStaticManifest:Z

.field public final disableLiveCaptioningOnPlayerInit:Z

.field public final disableLoadingRetryOnFatalError:Z

.field public final disableNetworkErrorCountInChunkSource:Z

.field public final disablePoolingForDav1dMediaCodec:Z

.field public final disablePreallocateCodecDuringStartup:Z

.field public final disableRecoverInBackground:Z

.field public final disableSecondPhasePrefetchForDataSaver:Z

.field public final disableSecondPhasePrefetchForReels:Z

.field public final disableSecondPhasePrefetchOnAppScrolling:Z

.field public final disableSkipInlineForHuddle:Z

.field public final disableSpeedAdjustmentOnBadUserExperience:Z

.field public final disableStoriesCustomizedUnstallBuffer:Z

.field public final disableTextEraLoggingOnLoadRetry:Z

.field public final disableTextRendererOn404InitSegmentLoadError:Z

.field public final disableTextRendererOn404LoadError:Z

.field public final disableTextRendererOn500InitSegmentLoadError:Z

.field public final disableTextRendererOn500LoadError:Z

.field public final disableTextTrackOnMissingTextTrack:Z

.field public final disableTigonBandwidthLogging:Z

.field public final disableUllBasedOnHoldout:Z

.field public final disableVideoTrackForInVisibleVDD:Z

.field public final dontRetry403OnExpiredUrl:Z

.field public final drmSessionStoreCapacity:I

.field public final dummyDefaultSetting:Z

.field public final dynamicDiscontinuityInitialPosMs:I

.field public final dynamicInfoSetting:LX/8CD;

.field public final earlyPreallocateCodecOnAppNotScrolling:Z

.field public final earlyPreallocateCodecOnIdle:Z

.field public final enable204SegmentRemapping:Z

.field public final enable404SegmentRemapping:Z

.field public final enable416Logging:Z

.field public final enable500R1FallbackLogging:Z

.field public final enableAV1SRShader:Z

.field public final enableActiveDrmSessionStoreRelease:Z

.field public final enableAdBreakEnhancedPrefetch:Z

.field public final enableAdditionalDecoderInitFailureMessage:Z

.field public final enableAllLongerPrefetchAds:Z

.field public final enableAlwaysCallPreallocateCodec:Z

.field public final enableAsynchronousBufferQueueing:Z

.field public final enableAudioTrackRetry:Z

.field public final enableAv1Dav1d:Z

.field public final enableAv1LibGav1:Z

.field public final enableAvc1ColorConfigParseFix:Z

.field public final enableBackgroundServicePlayerReuse:Z

.field public final enableBackwardJumpSeekKeyframeSync:Z

.field public final enableBitrateAwareAudioPrefetch:Z

.field public final enableBlackscreenDetector:Z

.field public final enableBlockListingResource:Z

.field public final enableBoostOngoingPrefetchPriorityPlay:Z

.field public final enableBoostOngoingPrefetchPriorityPrepare:Z

.field public final enableBufferAwareJumpSeek:Z

.field public enableBusySignalToFramework:Z

.field public final enableCDNDebugHeaders:Z

.field public final enableCacheBlockWithoutTimeout:Z

.field public final enableCacheLookUp:Z

.field public final enableCacheNetworkTypeIfNotSet:Z

.field public final enableCachedBandwidthEstimate:Z

.field public final enableCancelFollowupPrefetch:Z

.field public final enableCancelOngoingPrefetchPause:Z

.field public final enableCancelOngoingRequestPause:Z

.field public final enableCancelPrefetchInQueuePrepare:Z

.field public final enableCaseInsensitiveHttpResponseHeaderKey:Z

.field public final enableCheckAudioError:Z

.field public final enableClearStallOnBroadcastEnd:Z

.field public final enableClockSync:Z

.field public final enableCodecDeadlockFix:Z

.field public final enableCodecHistoryOverlayField:Z

.field public final enableCodecPreallocation:Z

.field public final enableContinueLoadingLoggingForManifest:Z

.field public final enableContinueLoadingLoggingForMedia:Z

.field public final enableCreateByteBufferFromABufferNullCheckHooks:Z

.field public final enableCustomizedDRCEffect:Z

.field public final enableCustomizedDRCForHeadset:Z

.field public final enableCustomizedPrefetchThreadPriority:Z

.field public final enableCustomizedXHEAACConfig:Z

.field public final enableDashManifestPool:Z

.field public final enableDav1dAsMediaCodecAdapter:Z

.field public final enableDav1dOpenGLIncorrectSurfaceSizeFix:Z

.field public final enableDav1dOpenGLRendering:Z

.field public final enableDav1dOpenGLRenderingHandleAspectRatio:Z

.field public final enableDebugLogs:Z

.field public final enableDeduplicateImfEmsgAtPlayer:Z

.field public final enableDelayWarmupRunning:Z

.field public final enableDemoteOngoingPrefetchPriorityPause:Z

.field public final enableDrmProvisioningRetry:Z

.field public final enableDrmSessionStore:Z

.field public final enableDynamicCursorDistance:Z

.field public final enableDynamicDiscontinuityDistance:Z

.field public final enableDynamicMinRebufferMsController:Z

.field public enableDynamicPrefetchCacheFileSize:Z

.field public enableDynamicPrefetchCacheFileSizePrefetchOnly:Z

.field public final enableE2ECDNTracing:Z

.field public final enableEmsgPtsAlignment:Z

.field public final enableEmsgTrackForAll:Z

.field public final enableEnsureBindService:Z

.field public final enableEvictCacheOnExoplayerErrors:Z

.field public final enableEvictPlayerOnAudioTrackInitFailed:Z

.field public final enableExcessiveNumUriRedirectLogging:Z

.field public final enableExplicitTextDataSourceCreation:Z

.field public final enableFBLiteHttpDataSource:Z

.field public final enableFallbackToMainProcess:Z

.field public final enableFillBufferHooks:Z

.field public final enableFillFreeBufferCheckNodeHooks:Z

.field public final enableFirstWarmUpRequestOnScreen:Z

.field public final enableFixForOnPreparingCallback:Z

.field public final enableFixRemovePlayerViewFromParent:Z

.field public final enableFixTrackIndexOOB:Z

.field public final enableFrameBasedLogging:Z

.field public final enableFreeNodeHooks:Z

.field public final enableGlobalNetworkMonitor:Z

.field public final enableGlobalStallMonitor:Z

.field public final enableGrootAlwaysSendPlayStarted:Z

.field public final enableHeroPlayerMaxLoopCount:Z

.field public final enableHttpPriorityForPrefetch:Z

.field public final enableHttpPriorityForStreaming:Z

.field public final enableHybridCacheForPrefetch:Z

.field public final enableIgHttpDataSource:Z

.field public final enableInstreamAdsEmsgLog:Z

.field public final enableIsTextAdaptationSetNotFoundLogging:Z

.field public final enableJumpTrackFallingBehind:Z

.field public final enableKillProcessBeforeRebind:Z

.field public final enableKillVideoProcessForAudioTrackInitFailed:Z

.field public final enableKillVideoProcessForIllegalStateException:Z

.field public final enableLastPlaybackSpeedCacheUpdate:Z

.field public final enableLatencyManagerRateLimiting:Z

.field public final enableLatencyPlaybackSpeed:Z

.field public final enableLazyAudioLoadForProgressive:Z

.field public final enableLiveBWEstimation:Z

.field public final enableLiveBroadcastErrorUI:Z

.field public final enableLiveBufferMeter:Z

.field public final enableLiveJumpByTrimBuffer:Z

.field public final enableLiveLatencyManager:Z

.field public final enableLiveOneTimeLoadingJump:Z

.field public final enableLiveTierSpecificBufferSetting:Z

.field public final enableLiveTierSpecificRebuffer:Z

.field public final enableLoadErrorHandlingPolicy:Z

.field public final enableLoaderRetryLoggingForManifest:Z

.field public final enableLoaderRetryLoggingForMedia:Z

.field public final enableLocalSocketProxy:Z

.field public final enableLogExceptionMessageOnError:Z

.field public final enableLogSemiCachedEvents:Z

.field public final enableLoggingEmptyOrNullVideoId:Z

.field public final enableLongCacheKeyForContentLength:Z

.field public final enableLowLatencyDecoding:Z

.field public final enableLowLatencyDecodingOverrideSDKGating:Z

.field public final enableMP3Extractor:Z

.field public final enableMediaCodecPoolingForLiveAudio:Z

.field public final enableMediaCodecPoolingForLiveVideo:Z

.field public final enableMediaCodecPoolingForProgressiveAudio:Z

.field public final enableMediaCodecPoolingForProgressiveVideo:Z

.field public final enableMediaCodecPoolingForVodAudio:Z

.field public final enableMediaCodecPoolingForVodVideo:Z

.field public final enableMediaCodecReuseOptimizeLock:Z

.field public final enableMediaCodecReuseOptimizeRelease:Z

.field public final enableMediaSessionControls:Z

.field public final enableMemoryAwareBufferSizeUsingRed:Z

.field public final enableMemoryAwareBufferSizeUsingYellow:Z

.field public final enableMixeCodecManifestLogging:Z

.field public final enableMixeCodecManifestVideoCodecSwitchedLogging:Z

.field public final enableMixedCodecManifestSupport:Z

.field public final enableMp3Mp4ExtractorLogic:Z

.field public final enableMp4MultiTrafBoxesFix:Z

.field public final enableMpdFilteringUtils:Z

.field public final enableNeedCenteringIndependentlyGroot:Z

.field public final enableOffloadInitHeroService:Z

.field public final enableOffloadingIPC:Z

.field public final enableOnMessageReceivedHooks:Z

.field public final enableOnOMXEmptyBufferDoneHooks:Z

.field public final enableOneSemanticsLoaderRetry:Z

.field public final enableOpenGLSurfaceSizeUpdateFix:Z

.field public final enableOverrideBufferWatermark:Z

.field public final enableOverrideEndPosition:Z

.field public final enablePCMBufferListener:Z

.field public final enablePIDForHuddle:Z

.field public final enablePauseNow:Z

.field public final enablePlayerActionStateLoggingInFlytrap:Z

.field public final enablePreSeekToApi:Z

.field public final enablePredictedUrlTracing:Z

.field public final enablePrefetchCancelCallback:Z

.field public final enableProgressiveFallbackWhenNoRepresentations:Z

.field public final enableProgressivePrefetchWhenNoRepresentations:Z

.field public final enableQuickDashPlayback:Z

.field public final enableRebootDeviceErrorUIForAudioTrackInitFailed:Z

.field public final enableRebootDeviceErrorUIForCodecInitFailed:Z

.field public final enableRebootDeviceErrorUIForIllegalStateException:Z

.field public final enableReduceRetryBeforePlay:Z

.field public final enableRequestAnalyticsTagsHeaderLogging:Z

.field public final enableRequestEtdHeader:Z

.field public final enableRetryErrorLoggingInCancel:Z

.field public final enableRetryOnConnection:Z

.field public final enableRetryWarmup:Z

.field public final enableSaturation:Z

.field public final enableSeamlessAudioCodecAdaptation:Z

.field public final enableSecondPhaseAlignment:Z

.field public final enableSecondPhasePrefetch:Z

.field public final enableSecondPhasePrefetchWebm:Z

.field public final enableSecondaryChannelLoggingForLite:Z

.field public final enableSegmentIndexCheckForPrefetchBytes:Z

.field public final enableSendCommandHooks:Z

.field public final enableServerSideAbr:Z

.field public final enableServerSideForwardBwe:Z

.field public final enableServerSideForwardTracing:Z

.field public final enableSpatialOpusRendererExo2:Z

.field public final enableSsBweHeaderForLive:Z

.field public final enableStopWarmupSchedulerEmpty:Z

.field public final enableStreamLatencyToggleOverride:Z

.field public final enableSuspensionAfterBroadcasterStall:Z

.field public final enableSynchronizeCodecInteractionsWithQueueing:Z

.field public final enableSystrace:Z

.field public final enableTextTrackWithKnownLanguage:Z

.field public final enableTransferListenerCallbackPerfFix:Z

.field public final enableUnexpectedExoExceptionLogging:Z

.field public final enableUnifiedGrootErrorHandling:Z

.field public final enableUpdateProgressiveContentLengthFromCache:Z

.field public final enableUsingASRCaptions:Z

.field public final enableVideoDebugEventLogging:Z

.field public final enableVideoHybridCache:Z

.field public final enableVideoMemoryCache:Z

.field public final enableVideoPlayerServerSideBweAnnotations:Z

.field public final enableVideoPositionLoggingInCompleteEvent:Z

.field public final enableVodContentLengthLogging:Z

.field public final enableVodDrmPrefetch:Z

.field public final enableVodPausedLoading:Z

.field public final enableVp9CodecPreallocation:Z

.field public final enableVrlQplLoggingEvents:Z

.field public final enableWarmCodec:Z

.field public final enableWarmUpRequestOffscreen:Z

.field public final enableWarmupProcessPeriodically:Z

.field public final enableWarmupScheduler:Z

.field public final enableWarmupSchedulerRightAway:Z

.field public final enableWarmupSkipScheduler:Z

.field public final enableWifiLockManager:Z

.field public final enableWifiLongerPrefetchAds:Z

.field public final enabledViewManagementInGroot:Z

.field public final enforceSizeLimitOnSecondPhasePrefetch:Z

.field public final enhanceParseException:Z

.field public final errorRecoveryAttemptRepeatCountFlushThreshold:I

.field public final exceedRendererCapabilitiesIfAllFilteredOut:Z

.field public final excessiveUriRedirectLoggingLimit:I

.field public final exo2ReuseManifestAfterInitialParse:Z

.field public final exo2Vp9UseSurfaceRenderer:Z

.field public final exoPlayerUpgrade218verifyApplicationThread:Z

.field public final expBackOffSpeedUp:F

.field public final expBackoffInRetryBaseDelay:I

.field public final extendedApiTierLiveRebufferThresholdMs:I

.field public final extendedLiveRebufferThresholdMs:I

.field public final extendedMinRebufferThresholdMs:I

.field public final extendedPremiumTierLiveRebufferThresholdMs:I

.field public final fallbackToFirstSegment:Z

.field public final fbstoriesMinBufferMsConfig:LX/8CA;

.field public final fbstoriesMinRebufferMsConfig:LX/8CA;

.field public final fetchCacheSourceHttpConnectTimeoutMsConfig:LX/8CA;

.field public final fetchHttpReadTimeoutMsConfig:LX/8CA;

.field public final fixBlackscreenByRecreatingSurface:Z

.field public final fixDRMPlaybackOnHDMI:Z

.field public final fixNullCacheSpan:Z

.field public final fixPeriodTransitionWithNonZeroStartPosition:Z

.field public final fixSurfaceInvisibleParent:Z

.field public final fixXmlParserError:Z

.field public final forceAdjustSurfaceOnMainThread:Z

.field public final forceDisableULL:Z

.field public final forceMainThreadHandlerForHeroSurface:Z

.field public final forceManifestFilteringMode:I

.field public final forceMinWatermarkGreaterThanMinRebuffer:Z

.field public final forceOneSemanticsHandling:Z

.field public final forceOneSemanticsWaveHandling:I

.field public final forceSeekRushPlayback:Z

.field public final forceStereoToMonoConversion:Z

.field public final fragmentedMp4ExtractorVersion:I

.field public final frequentApiTierBroadcasterStallIntervalThresholdMs:I

.field public final frequentBroadcasterStallIntervalThresholdMs:I

.field public final frequentPremiumTierBroadcasterStallIntervalThresholdMs:I

.field public final frequentStallIntervalThresholdMs:I

.field public final fullscreenPredictionRequestTimeoutMs:J

.field public final getMinLoadPositionStartOfPlayback:Z

.field public final getPlaybackPrefFromPrefetchRequest:Z

.field public final globalStallCountsToUpdateDynamicRebuffer:I

.field public final globalStallCountsToUpdateLiveDynamicRebuffer:I

.field public final goodVsrScoreThreshold:I

.field public final handleReleasedReusedSurfaceTexture:Z

.field public final handlerThreadPoolSize:I

.field public final highJumpDistanceMs:I

.field public final huddleLatencyMaxSpeedDelta:F

.field public final ignore404AfterStreamEnd:Z

.field public final ignoreEmptyProfileLevels:Z

.field public final ignoreLiveStreamErrorsTimeoutMs:J

.field public final ignoreStreamErrorsTimeoutMs:J

.field public final ignoreTemplatedMinLoadPosition:Z

.field public final improveLooping:Z

.field public final includeAllBufferingEvents:Z

.field public final includeLiveTraceHeader:Z

.field public final includePlaybackSessionIdHeader:Z

.field public final initChunkCacheSize:I

.field public final initialBufferTrimPeriodMs:I

.field public final initialBufferTrimTargetMs:I

.field public final initialBufferTrimThresholdMs:I

.field public final intentBasedBufferingConfig:LX/8CJ;

.field public final isAbrTracingEnabled:Z

.field public final isAudioDataSummaryEnabled:Z

.field public final isDefaultMC:Z

.field public final isEarlyPreallocateCodec:Z

.field public final isExo2AggresiveMicrostallFixEnabled:Z

.field public final isExo2DrmEnabled:Z

.field public final isExo2MediaCodecReuseEnabled:Z

.field public final isExo2UseAbsolutePosition:Z

.field public final isExo2Vp9Enabled:Z

.field public final isLiveTraceEnabled:Z

.field public final isMeDevice:Z

.field public final isSetSerializableBlacklisted:Z

.field public final isTATracingEnabled:Z

.field public final isVideoQplPipelineEnabled:Z

.field public final jumpSeekPosLeftoverBufferDurationMs:I

.field public final jumpSeekReductionFactorPct:I

.field public final killVideoProcessOnExoPlaybackExceptionMaximumRetryCount:I

.field public final killVideoProcessOnExoPlaybackExceptionRetryTimeMs:J

.field public final killVideoProcessWhenMainProcessDead:Z

.field public final largeBandwidthCursorMs:I

.field public final largeBandwidthToleranceMs:I

.field public final largeJumpBandwidthMultiplier:F

.field public final lateNightHourLowerThreshold:I

.field public final lateNightHourUpperThreshold:I

.field public final latencyBoundMsConfig:LX/8CA;

.field public final latencyControllerBypassLimits:Z

.field public final liveAPIMinBufferMsConfig:LX/8CA;

.field public final liveAPIMinRebufferMsConfig:LX/8CA;

.field public final liveBufferDurationFluctuationTolerancePercent:I

.field public final liveBufferMeterTrimByMinBuffer:Z

.field public final liveDashEdgeLatencyMs:I

.field public final liveDashHighWatermarkMs:I

.field public final liveDashLowWatermarkMs:I

.field public final liveEnableStreamingCache:Z

.field public final liveLatencyManagerPlayerFormat:Ljava/lang/String;

.field public final liveLatencySettings:Ljava/util/Map;

.field public final liveMinBufferMsConfig:LX/8CA;

.field public final liveMinRebufferMsConfig:LX/8CA;

.field public final liveMinRetryCounts:I

.field public final livePremiumMinBufferMsConfig:LX/8CA;

.field public final livePremiumMinRebufferMsConfig:LX/8CA;

.field public final livePrioritizeTimeOverSizeThresholds:Z

.field public final liveTrimByBufferMeterMinDeltaMs:I

.field public final liveUseLowPriRequests:Z

.field public final localSocketProxyAddress:Ljava/lang/String;

.field public final logLatencyEvents:Z

.field public final logOnApacheFallback:Z

.field public final logPausedSeekPositionBeforeSettingState:Z

.field public final logStallOnPauseOnError:Z

.field public final loggerSDKConfig:LX/8CB;

.field public final lowJumpDistanceMs:I

.field public final mEventLogSetting:LX/8C4;

.field public final mLowLatencySetting:LX/8C5;

.field public final manifestErrorReportingExo2:Z

.field public final manifestMisalignmentReportingExo2:Z

.field public maxAllowed503RetryCount:I

.field public final maxBufferDurationPausedLiveUs:J

.field public final maxBufferToDownloadInPausedLoadingMs:I

.field public final maxBytesToPrefetchCellVOD:I

.field public final maxBytesToPrefetchVOD:I

.field public final maxCustomizedWABufferMs:I

.field public final maxDistanceBetweenTracksMs:I

.field public final maxDurationUsForFullSegmentPrefetch:J

.field public final maxMediaCodecInstancesPerCodecName:I

.field public final maxMediaCodecInstancesTotal:I

.field public final maxNumGapsToNotify:I

.field public final maxNumRedirects:I

.field public final maxPastOtherTrackDistanceMs:I

.field public final maxPredictedSegmentsToRemap:I

.field public final maxRetryCountByEvictCacheOnExoplayerErrors:I

.field public final maxRetryCountByEvictPlayerOnAudioTrackInitFailed:I

.field public final maxSegmentsToAdvance:J

.field public final maxSegmentsToPredict:I

.field public final maxStaleManifestCountForDiscontinuityJumps:I

.field public final maxTimeAllowedSpentInPausedLoadingMs:I

.field public final maxTimeMsSinceRefreshPDash:I

.field public final maxTimeToSkipInlineManifestMs:I

.field public final maxTrackJumpsAllowed:I

.field public final maxWidthForAV1SRShader:I

.field public final maxWifiBytesToPrefetchAds:I

.field public final maxWifiPrefetchDurationMsAds:I

.field public final maybeSkipInlineManifestForLSB:Z

.field public final mcDebugState:Ljava/lang/String;

.field public final mcValueSource:Ljava/lang/String;

.field public final microStallThresholdMsToUseMinBuffer:I

.field public final minBufferForPreSeekMs:J

.field public final minBufferMsConfig:LX/8CA;

.field public final minBufferedDurationMsToCancel:I

.field public minCacheFileSizeForDynamicChunkingInBytes:J

.field public final minCustomizedWABufferMs:I

.field public final minDelayToRefreshTigonBitrateMs:J

.field public final minLiveStartPositionMs:I

.field public final minMicroRebufferMsConfig:LX/8CA;

.field public final minNumManifestForOutOfBoundsPDash:I

.field public final minRebufferMsConfig:LX/8CA;

.field public final minRetryCountBeforePlay:I

.field public final minScoreThresholdForLL:I

.field public final minTimeBetweenDynamicCursorChangesMs:I

.field public final minTimeBetweenStallToIgnoreDiscontJumpS:I

.field public final minTimeToSkipInlineManifestMs:I

.field public final minimumLogLevel:I

.field public final minimumTimeBetweenSpeedChangesS:I

.field public final minimumTimeBetweenStallsS:I

.field public final needUpdatePlayerStateThresholdMs:I

.field public final needUpdateStateByPositionOffsetThresholdMs:I

.field public final networkAwareDisableSecondPhasePrefetch:LX/8CA;

.field public final networkAwareHttpPriorityIncrementalForStreaming:LX/8CA;

.field public final networkAwarePrefetchTaskQueueWorkerNum:LX/8CA;

.field public final newDownstreamFormatChange:Z

.field public final numDashChunkMemoryCacheSampleStreams:I

.field public final numMsToPrefetch:I

.field public final numOfBytesBeforeLoaderThreadSleep:I

.field public final numSegmentsToSecondPhasePrefetch:I

.field public final numSegmentsToSecondPhasePrefetchAudio:I

.field public final numSegmentsToSecondPhasePrefetchXHEAACAudio:I

.field public final offloadGrootAudioFocus:Z

.field public final oneSemanticsOsParamValue:Ljava/lang/String;

.field public final originAllowlistForAlternateCodec:Ljava/util/Set;

.field public final parseAndAttachETagManifest:Z

.field public final parseManifestIdentifier:Z

.field public final pausePlayingVideoWhenRelease:Z

.field public final pausedLoadingTriggerTypes:Ljava/util/Set;

.field public final pidMultiplierFloor:F

.field public final pidParameterExpBackOff:F

.field public final pidParameterMultiplierInitial:F

.field public final playbackAboutToFinishCallbackTriggeringRemainingDuration:I

.field public final playerOriginPausedLoadingBlackList:Ljava/lang/String;

.field public final playerPoolSize:I

.field public final playerRespawnExo2:Z

.field public final playerWarmUpPoolSize:I

.field public final playerWarmUpWatermarkMs:I

.field public final playerWatermarkBeforePlayedMs:I

.field public final postStoriesGrootPrefetchToHeroManagerThread:Z

.field public final predictedHuddleDashManifestReadTimeoutMs:I

.field public final predictedLiveDashManifestReadTimeoutMs:I

.field public final predictionMaxSegmentDurationMs:I

.field public final predictiveDashReadTimeoutMs:I

.field public final predictiveDashSetting:LX/8CT;

.field public final prefetchAudioFirst:Z

.field public final prefetchAudioFirstForStoriesAds:Z

.field public final prefetchBypassFilter:Z

.field public final prefetchSubOriginBlockList:Ljava/lang/String;

.field public final prefetchTagBlockList:Ljava/lang/String;

.field public final prefetchTaskQueuePutInFront:Z

.field public final prefetchTaskQueueRetryNumber:I

.field public final prefetchTaskQueueSize:I

.field public final prefetchTaskQueueWorkerNum:I

.field public final prefetchThreadUpdatedPriority:I

.field public final prefetchUrgentTaskQueueWorkerNum:I

.field public final preventAdjustWhenSurfaceNotValid:Z

.field public final preventJumpStaticManifest:Z

.field public final preventPreallocateIfNotEmpty:Z

.field public final preventTextRendererDelay:Z

.field public final preventWarmupInvalidSource:Z

.field public final prioritizeAv1Dav1dOverLibgav1:Z

.field public final prioritizeAv1HardwareDecoder:Z

.field public final prioritizeTimeOverSizeThresholds:Z

.field public final progressivePrefetchBytesCell:I

.field public final progressivePrefetchBytesWifi:I

.field public final proxyDrmProvisioningRequests:Z

.field public final qualityMapperBoundMsConfig:LX/8CA;

.field public final quitHandlerSafely:Z

.field public final redMemoryBufferSizeMultiplier:D

.field public final reduceMemoryDataSinkMemorySpike:Z

.field public final refreshManifestAfterInit:Z

.field public final refreshManifestOnPredictionRestriction:Z

.field public final releaseGrootSurfaceSync:Z

.field public final releaseHeroManagerWhenLowMemInBg:Z

.field public final releaseSurfaceBlockTimeoutMS:I

.field public final releaseSurfaceInServicePlayerReset:Z

.field public final releaseThreadInterval:I

.field public final removeGifPrefixForDRMKeyRequest:Z

.field public final renderRetryTimeMs:I

.field public final rendererAllowedJoiningTimeMs:J

.field public final reorderSeekPrepare:Z

.field public final reportExceptionAsMME:Z

.field public final reportExceptionsAsSoftErrors:Z

.field public final reportLastVideoInCrash:Z

.field public final reportPrefetchAbrDecision:Z

.field public final reportStallThresholdMs:I

.field public final reportStallThresholdMsLatencyManager:I

.field public final reportUnexpectedStopLoading:Z

.field public final resizeAndRepositionGrootSurfaceControl:Z

.field public final respectAbrForUll:Z

.field public final respectAbrIndexForUll:Z

.field public final respectDroppedQualityFlag:Z

.field public final respectDynamicPlayerSettings:Z

.field public final restartServiceThresholdMs:I

.field public final retryCountsForStartPlayManifest503:I

.field public final retryCountsForStartPlayManifestFetch:I

.field public final returnRequestedSeekTimeTimeoutMs:I

.field public final saturationFactor:F

.field public final scalingBufferErrorMs:I

.field public final sdKVersionToUseCustomizedBuffering:I

.field public final sdKVersionToUseTargetBufferOverwrite:I

.field public final sdkVersionToBypassHeroStateRefresh:I

.field public final sdkVersionToUseConservativeLoadControl:I

.field public final sdkVersionToUseDefaultLoadControl:I

.field public final secondPhasePrefetchQueueMaxSize:I

.field public final secondaryChannelLoggingMaxDisplayedFramesStringSize:I

.field public final secondaryChannelLoggingMaxNumOfFramesInOneJson:I

.field public final secondaryChannelLoggingSamplingFactor:I

.field public final seekParameterOptionIndex:I

.field public final segDurationMultiplier:I

.field public final serviceInjectorClassName:Ljava/lang/String;

.field public final setPlayWhenReadyOnError:Z

.field public final setPlayWhenReadyOnRetry:Z

.field public final shareBWEEstimateAcrossVideos:Z

.field public final shouldAddDefaultMP4Extractor:Z

.field public final shouldAlwaysDo503Retry:Z

.field public final shouldCleanupHeroManagerThread:Z

.field public final shouldDisableAV1VideoTrackOnlyforVDD:Z

.field public final shouldExcludeAbsolutePositionForClippingMediaSource:Z

.field public final shouldLoadBinaryDataFromManifest:Z

.field public final shouldLogInbandTelemetryBweDebugString:Z

.field public final shouldPrefetchSecondSegmentOffset:Z

.field public final shouldUseWarmupSlot:Z

.field public final shouldWarmupAwareOfAppScrolling:Z

.field public final showDebugStats:Z

.field public final skipAV1PreviousKeyFrameSeek:Z

.field public final skipAudioMediaCodecStopOnRelease:Z

.field public final skipAudioPrefetch:Z

.field public final skipDebugLogs:Z

.field public final skipEvaluateIflastChunkWasInitialization:Z

.field public final skipInlineManifestForLsbConfPercentile:I

.field public final skipInvalidSamples:Z

.field public final skipMediaCodecStopOnRelease:Z

.field public final skipPrefetchInCacheManager:Z

.field public final skipReleaseSurfaceBlock:Z

.field public final skipSurfaceViewReparentOnSetCurrentView:Z

.field public final skipSurfaceViewTransactionOnSameSurface:Z

.field public final skipSynchronizedUpdatePriority:Z

.field public final skipThumbnailCacheKey:Z

.field public final smallBandwidthCursorMs:I

.field public final smallBandwidthToleranceMs:I

.field public final smallJumpBandwidthMultiplier:F

.field public final smartGcEnabled:Z

.field public final smartGcTimeout:I

.field public final softErrorErrorCodeBlacklist:Ljava/util/Set;

.field public final softErrorErrorDomainBlacklist:Ljava/util/Set;

.field public final softErrorErrorMessageBlacklist:Ljava/util/Set;

.field public final sortSubripSubtitles:Z

.field public final splitBweOnRadio:Z

.field public final splitLastSegmentCachekey:Z

.field public final ssAbrAlphaDecay:F

.field public final ssAbrExperimentSetting:Ljava/lang/String;

.field public final ssAbrMinSamples:I

.field public final ssAbrNumSamplesAvg:I

.field public final staleManifestThreshold:I

.field public final staleManifestThresholdToShowInterruptUI:I

.field public final stallCountsToUpdateDynamicRebufferThreshold:I

.field public final stallFromSeekThresholdMs:I

.field public final stopRefreshingManifestNoPlaybackUpdateAfterTimeMs:I

.field public final streamLatencyToggleMaxSpeedDelta:F

.field public final streamLatencyTogglePIDDesiredBufferMs:I

.field public final streamLatencyTogglePIDIntegralBoundMs:I

.field public final streamLatencyToggleSpeedUpBandwidthMultiplier:F

.field public final streamLatencyToggleStateOverride:I

.field public final subtitleDurationToMaxValue:Z

.field public final surfaceControlForceVideoSizeUpdate:Z

.field public final surfaceMPDFailoverImmediately:Z

.field public final swallowSurfaceGlDetachError:Z

.field public final targetBufferBytesFactor:F

.field public final targetBytesForOverwrite:I

.field public final timeBetweenPIDSamplesMs:I

.field public final tslogSettings:LX/8C7;

.field public final unstallBufferSetting:LX/8CL;

.field public final unstallBufferSettingLive:LX/8CL;

.field public final updateConcatMsDuringPlayback:Z

.field public final updateLoadingPriorityExo2:Z

.field public final updateParamOnGetManifestFetcher:Z

.field public final updateUnstallBufferDuringPlayback:Z

.field public final useAccumulatorForBw:Z

.field public final useAdAwareLoadControl:Z

.field public final useAllSettingsToSupportLowerLatency:Z

.field public final useBackgroundHandlerForHeroLiveManager:Z

.field public final useBlockingSetSurfaceExo2:Z

.field public final useBufferBasedAbrPDash:Z

.field public final useBufferedCacheDataSink:Z

.field public final useBwBpsForConnectionQuality:Z

.field public final useCellMaxWaterMarkMsConfig:Z

.field public final useCodecNeedsEosBufferTimestampWorkaround:Z

.field public final useDefaultTrackSelector:Z

.field public final useDummySurfaceExo2:Z

.field public final useExoPlayerBuilder:Z

.field public final useFallbackLogging:Z

.field public final useForceSurfaceChange:Z

.field public final useFullscreenTransitionPrediction:Z

.field public final useHandlerThreadPool:Z

.field public final useHeroBufferSize:Z

.field public final useHttpPriorityIncrementalForLongBufferedStreaming:Z

.field public final useHttpPriorityIncrementalForPrefetch:Z

.field public final useHttpPriorityIncrementalForStreaming:Z

.field public final useHttpPriorityWarmupForLongBufferedStreaming:Z

.field public final useInterruptedIoException:Z

.field public final useIsCachedSkipInit:Z

.field public final useLatencyForSegmentConcat:Z

.field public final useLowPriorityForSecondPhasePrefetch:Z

.field public final useLowerHttpPriorityForAllPrefetch:Z

.field public final useLowerHttpPriorityForUnimportantPrefetch:Z

.field public final useMainThreadForHeroPlayer:Z

.field public final useMaxBufferForProgressive:Z

.field public final useMaxOfLowWatermarkOrPrevHighWaterMarkWhenForced:Z

.field public final useMediaCodecPoolingConcurrentCollections:Z

.field public final useMediaCodecPoolingForCodecByName:Ljava/lang/String;

.field public final useMinIntentBasedWatermarkBeforePlay:Z

.field public final useMultiPeriodBufferCalculation:Z

.field public final useNetworkAwareHttpPriorityIncrementalForStreaming:Z

.field public final useNetworkAwareSettingsForLargerChunk:Z

.field public final useNetworkAwareSettingsForUnstallBuffer:Z

.field public final useNetworkAwaretPrefetchTaskQueueWorkerNum:Z

.field public final useNonInterleavedExtractorForLocal:Z

.field public final useOutputSurfaceWorkaround:Z

.field public final usePerVideoLookupToCheckCache:Z

.field public final usePrefetchFilter:Z

.field public final usePrefetchSegmentOffset:Z

.field public final useSSAbrBWE:Z

.field public final useSSAbrMinRtt:Z

.field public final useShortKey:Z

.field public final useSimpleSpeedController:Z

.field public final useSingleCachedBandwidthEstimate:Z

.field public final useSsBweForVod:Z

.field public final useSteadyStateToControlSpeed:Z

.field public final useThreadSafeStandaloneClock:Z

.field public final useVersion2_18Workarounds:Z

.field public final useVideoSourceAsWarmupKey:Z

.field public final useWAPlayerPoolLoadControl:Z

.field public final useWatermarkEvaluatorForProgressive:Z

.field public final useWifiMaxWaterMarkMsConfig:Z

.field public final userAgent:Ljava/lang/String;

.field public final userId:Ljava/lang/String;

.field public final validateBytesToFallbackOnFirstSegment:Z

.field public final videoBufferSize:I

.field public final videoMemoryCacheSizeKb:I

.field public final videoPrefetchSetting:LX/8C9;

.field public final vp9BlockingReleaseSurface:Z

.field public final vp9PlaybackDecoderName:Ljava/lang/String;

.field public final wakelockOriginLists:Ljava/util/Set;

.field public final warmupAv1Codec:Z

.field public final warmupVp9Codec:Z

.field public final watchTimeThresholdToDisableFollowupPrefetch:F

.field public final watchTimeThresholdToDisableSecondPhasePrefetchSeconds:F

.field public final wifiMaxWatermarkMsConfig:LX/8CA;

.field public final xHEAACCEffectType:I

.field public final xHEAACTargetReferenceLvl:I


# direct methods
.method public static constructor <clinit>()V
    .locals 2

    new-instance v1, LX/7OH;

    invoke-direct {v1}, LX/7OH;-><init>()V

    new-instance v0, LX/8CU;

    invoke-direct {v0, v1}, LX/8CU;-><init>(LX/7OH;)V

    sput-object v0, LX/8CU;->A01:LX/8CU;

    new-instance v1, LX/74e;

    invoke-direct {v1}, LX/74e;-><init>()V

    new-instance v0, Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

    invoke-direct {v0, v1}, Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;-><init>(LX/74e;)V

    sput-object v0, LX/8CU;->A00:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

    return-void
.end method

.method public constructor <init>(LX/7OH;)V
    .locals 3

    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    const/4 v1, 0x0

    iput-boolean v1, p0, LX/8CU;->enableCacheNetworkTypeIfNotSet:Z

    iget-object v0, p1, LX/7OH;->A0N:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

    iput-object v0, p0, LX/8CU;->autogenSettings:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

    iput-boolean v1, p0, LX/8CU;->improveLooping:Z

    const/4 v0, 0x0

    iput-object v0, p0, LX/8CU;->serviceInjectorClassName:Ljava/lang/String;

    iget v0, p1, LX/7OH;->A07:I

    iput v0, p0, LX/8CU;->playerPoolSize:I

    const/16 v0, 0x7d0

    iput v0, p0, LX/8CU;->releaseSurfaceBlockTimeoutMS:I

    iput-boolean v1, p0, LX/8CU;->skipReleaseSurfaceBlock:Z

    iget-object v0, p1, LX/7OH;->A0U:Ljava/lang/String;

    iput-object v0, p0, LX/8CU;->userAgent:Ljava/lang/String;

    const/4 v0, 0x0

    iput-object v0, p0, LX/8CU;->userId:Ljava/lang/String;

    const/16 v0, 0x14

    iput v0, p0, LX/8CU;->reportStallThresholdMs:I

    iput v0, p0, LX/8CU;->reportStallThresholdMsLatencyManager:I

    const/16 v0, 0xa

    iput v0, p0, LX/8CU;->checkPlayerStateMinIntervalMs:I

    const/16 v0, 0xc8

    iput v0, p0, LX/8CU;->checkPlayerStateMaxIntervalMs:I

    const/4 v0, 0x5

    iput v0, p0, LX/8CU;->checkPlayerStateIntervalIncreaseMs:I

    const/16 v0, 0xfa

    iput v0, p0, LX/8CU;->needUpdatePlayerStateThresholdMs:I

    const/16 v0, 0xa

    iput v0, p0, LX/8CU;->needUpdateStateByPositionOffsetThresholdMs:I

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/8CU;->enablePauseNow:Z

    iput-boolean v1, p0, LX/8CU;->enableFBLiteHttpDataSource:Z

    iput-boolean v1, p0, LX/8CU;->enableLocalSocketProxy:Z

    const/4 v0, 0x0

    iput-object v0, p0, LX/8CU;->localSocketProxyAddress:Ljava/lang/String;

    iput-boolean v1, p0, LX/8CU;->useNonInterleavedExtractorForLocal:Z

    iput-boolean v1, p0, LX/8CU;->enableIgHttpDataSource:Z

    iput-boolean v1, p0, LX/8CU;->enableCaseInsensitiveHttpResponseHeaderKey:Z

    iput-boolean v1, p0, LX/8CU;->usePrefetchFilter:Z

    iput-boolean v1, p0, LX/8CU;->avoidServiceClassLoadOnClient:Z

    iput-boolean v1, p0, LX/8CU;->vp9BlockingReleaseSurface:Z

    iput-object v0, p0, LX/8CU;->vp9PlaybackDecoderName:Ljava/lang/String;

    iput-boolean v1, p0, LX/8CU;->includeAllBufferingEvents:Z

    iget-object v0, p1, LX/7OH;->A0M:LX/8CC;

    iput-object v0, p0, LX/8CU;->cache:LX/8CC;

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/8CU;->setPlayWhenReadyOnError:Z

    iput-boolean v0, p0, LX/8CU;->setPlayWhenReadyOnRetry:Z

    const/16 v0, 0x3e8

    iput v0, p0, LX/8CU;->returnRequestedSeekTimeTimeoutMs:I

    const/16 v0, 0x1f4

    iput v0, p0, LX/8CU;->stallFromSeekThresholdMs:I

    iput-boolean v1, p0, LX/8CU;->enablePrefetchCancelCallback:Z

    iget-object v0, p1, LX/7OH;->A0R:LX/8CL;

    iput-object v0, p0, LX/8CU;->unstallBufferSetting:LX/8CL;

    iget-object v0, p1, LX/7OH;->A0S:LX/8CL;

    iput-object v0, p0, LX/8CU;->unstallBufferSettingLive:LX/8CL;

    iput-boolean v1, p0, LX/8CU;->clearBufferingWhenInWarmup:Z

    iget-object v0, p1, LX/7OH;->A0O:LX/8CJ;

    iput-object v0, p0, LX/8CU;->intentBasedBufferingConfig:LX/8CJ;

    iput-boolean v1, p0, LX/8CU;->releaseSurfaceInServicePlayerReset:Z

    iput-boolean v1, p0, LX/8CU;->respectDynamicPlayerSettings:Z

    iput-boolean v1, p0, LX/8CU;->reportPrefetchAbrDecision:Z

    iget-object v0, p1, LX/7OH;->A0K:LX/8CE;

    iput-object v0, p0, LX/8CU;->abrSetting:LX/8CE;

    iget-object v0, p1, LX/7OH;->A0J:LX/8CT;

    iput-object v0, p0, LX/8CU;->predictiveDashSetting:LX/8CT;

    iput-boolean v1, p0, LX/8CU;->refreshManifestOnPredictionRestriction:Z

    iget-object v0, p1, LX/7OH;->A0I:LX/8CD;

    iput-object v0, p0, LX/8CU;->dynamicInfoSetting:LX/8CD;

    const/4 v0, 0x0

    iput-object v0, p0, LX/8CU;->mLowLatencySetting:LX/8C5;

    iput-object v0, p0, LX/8CU;->mEventLogSetting:LX/8C4;

    iget-object v0, p1, LX/7OH;->A0L:LX/8C8;

    iput-object v0, p0, LX/8CU;->audioLazyLoadSetting:LX/8C8;

    iput-boolean v1, p0, LX/8CU;->enableLazyAudioLoadForProgressive:Z

    iget-object v0, p1, LX/7OH;->A0T:LX/8C9;

    iput-object v0, p0, LX/8CU;->videoPrefetchSetting:LX/8C9;

    const/16 v0, 0x3023

    iput v0, p0, LX/8CU;->dashLowWatermarkMs:I

    const/16 v0, 0x3747

    iput v0, p0, LX/8CU;->dashHighWatermarkMs:I

    iput-boolean v1, p0, LX/8CU;->liveEnableStreamingCache:Z

    const-wide/16 v0, 0x7d0

    iput-wide v0, p0, LX/8CU;->minDelayToRefreshTigonBitrateMs:J

    const/4 v0, 0x0

    iput-object v0, p0, LX/8CU;->fetchCacheSourceHttpConnectTimeoutMsConfig:LX/8CA;

    iput-object v0, p0, LX/8CU;->fetchHttpReadTimeoutMsConfig:LX/8CA;

    iput-object v0, p0, LX/8CU;->concatenatedMsPerLoadConfig:LX/8CA;

    iput-object v0, p0, LX/8CU;->minBufferMsConfig:LX/8CA;

    iput-object v0, p0, LX/8CU;->minRebufferMsConfig:LX/8CA;

    const/4 v1, 0x0

    iput-boolean v1, p0, LX/8CU;->enableGrootAlwaysSendPlayStarted:Z

    iput-object v0, p0, LX/8CU;->minMicroRebufferMsConfig:LX/8CA;

    iput-object v0, p0, LX/8CU;->liveMinBufferMsConfig:LX/8CA;

    iput-object v0, p0, LX/8CU;->liveMinRebufferMsConfig:LX/8CA;

    iput-object v0, p0, LX/8CU;->liveAPIMinBufferMsConfig:LX/8CA;

    iput-object v0, p0, LX/8CU;->liveAPIMinRebufferMsConfig:LX/8CA;

    iput-object v0, p0, LX/8CU;->livePremiumMinBufferMsConfig:LX/8CA;

    iput-object v0, p0, LX/8CU;->livePremiumMinRebufferMsConfig:LX/8CA;

    iput-boolean v1, p0, LX/8CU;->useLatencyForSegmentConcat:Z

    iget-object v0, p1, LX/7OH;->A0G:LX/8CA;

    iput-object v0, p0, LX/8CU;->latencyBoundMsConfig:LX/8CA;

    const/4 v0, 0x0

    iput-object v0, p0, LX/8CU;->fbstoriesMinBufferMsConfig:LX/8CA;

    iput-object v0, p0, LX/8CU;->fbstoriesMinRebufferMsConfig:LX/8CA;

    iget-object v0, p1, LX/7OH;->A0H:LX/8CA;

    iput-object v0, p0, LX/8CU;->qualityMapperBoundMsConfig:LX/8CA;

    iput-boolean v1, p0, LX/8CU;->enableProgressiveFallbackWhenNoRepresentations:Z

    iput-boolean v1, p0, LX/8CU;->blockDRMPlaybackOnHDMI:Z

    iput-boolean v1, p0, LX/8CU;->blockDRMScreenCapture:Z

    iput-boolean v1, p0, LX/8CU;->fixDRMPlaybackOnHDMI:Z

    iput-boolean v1, p0, LX/8CU;->enableWarmCodec:Z

    const/4 v0, 0x2

    iput v0, p0, LX/8CU;->playerWarmUpPoolSize:I

    const/16 v0, 0x3e8

    iput v0, p0, LX/8CU;->playerWatermarkBeforePlayedMs:I

    iput v0, p0, LX/8CU;->playerWarmUpWatermarkMs:I

    iput-boolean v1, p0, LX/8CU;->allowOverridingPlayerWarmUpWatermark:Z

    iput-boolean v1, p0, LX/8CU;->swallowSurfaceGlDetachError:Z

    iput-boolean v1, p0, LX/8CU;->forceMainThreadHandlerForHeroSurface:Z

    iput-boolean v1, p0, LX/8CU;->enableWarmupScheduler:Z

    iput-boolean v1, p0, LX/8CU;->enableWarmupSkipScheduler:Z

    iput-boolean v1, p0, LX/8CU;->enableWarmupSchedulerRightAway:Z

    const-wide/16 v0, 0x0

    iput-wide v0, p0, LX/8CU;->rendererAllowedJoiningTimeMs:J

    const/4 v1, 0x0

    iput-boolean v1, p0, LX/8CU;->skipPrefetchInCacheManager:Z

    iput-boolean v1, p0, LX/8CU;->useNetworkAwareSettingsForLargerChunk:Z

    iput-boolean v1, p0, LX/8CU;->enableDebugLogs:Z

    iput-boolean v1, p0, LX/8CU;->skipDebugLogs:Z

    iput-boolean v1, p0, LX/8CU;->showDebugStats:Z

    iput-boolean v1, p0, LX/8CU;->isAbrTracingEnabled:Z

    iget-boolean v0, p1, LX/7OH;->A0e:Z

    iput-boolean v0, p0, LX/8CU;->dummyDefaultSetting:Z

    iput-boolean v1, p0, LX/8CU;->enableCachedBandwidthEstimate:Z

    iput-boolean v1, p0, LX/8CU;->useSingleCachedBandwidthEstimate:Z

    iput-boolean v1, p0, LX/8CU;->disableTigonBandwidthLogging:Z

    iput-boolean v1, p0, LX/8CU;->shouldLogInbandTelemetryBweDebugString:Z

    iput-boolean v1, p0, LX/8CU;->killVideoProcessWhenMainProcessDead:Z

    iput-boolean v1, p0, LX/8CU;->isLiveTraceEnabled:Z

    iput-boolean v1, p0, LX/8CU;->isTATracingEnabled:Z

    iput-boolean v1, p0, LX/8CU;->releaseGrootSurfaceSync:Z

    iput-boolean v1, p0, LX/8CU;->asyncReleaseSurfaceOnMainThread:Z

    iput-boolean v1, p0, LX/8CU;->preventTextRendererDelay:Z

    iput-boolean v1, p0, LX/8CU;->fixPeriodTransitionWithNonZeroStartPosition:Z

    iput-boolean v1, p0, LX/8CU;->abrMonitorEnabled:Z

    const/16 v0, 0x3e8

    iput v0, p0, LX/8CU;->maxNumGapsToNotify:I

    iput-boolean v1, p0, LX/8CU;->enableMediaCodecPoolingForVodVideo:Z

    iput-boolean v1, p0, LX/8CU;->enableMediaCodecPoolingForVodAudio:Z

    iput-boolean v1, p0, LX/8CU;->enableMediaCodecPoolingForLiveVideo:Z

    iput-boolean v1, p0, LX/8CU;->enableMediaCodecPoolingForLiveAudio:Z

    iput-boolean v1, p0, LX/8CU;->enableMediaCodecPoolingForProgressiveVideo:Z

    iput-boolean v1, p0, LX/8CU;->enableMediaCodecPoolingForProgressiveAudio:Z

    iput-boolean v1, p0, LX/8CU;->enableMediaCodecReuseOptimizeLock:Z

    iput-boolean v1, p0, LX/8CU;->enableMediaCodecReuseOptimizeRelease:Z

    iput-boolean v1, p0, LX/8CU;->useMediaCodecPoolingConcurrentCollections:Z

    const/4 v0, 0x0

    iput-object v0, p0, LX/8CU;->useMediaCodecPoolingForCodecByName:Ljava/lang/String;

    iput-boolean v1, p0, LX/8CU;->useVersion2_18Workarounds:Z

    iput-boolean v1, p0, LX/8CU;->useCodecNeedsEosBufferTimestampWorkaround:Z

    const/16 v0, 0x3e8

    iput v0, p0, LX/8CU;->releaseThreadInterval:I

    const/4 v0, 0x2

    iput v0, p0, LX/8CU;->maxMediaCodecInstancesPerCodecName:I

    const/4 v0, 0x4

    iput v0, p0, LX/8CU;->maxMediaCodecInstancesTotal:I

    iput-boolean v1, p0, LX/8CU;->enableAlwaysCallPreallocateCodec:Z

    iput-boolean v1, p0, LX/8CU;->isEarlyPreallocateCodec:Z

    iput-boolean v1, p0, LX/8CU;->earlyPreallocateCodecOnAppNotScrolling:Z

    iput-boolean v1, p0, LX/8CU;->earlyPreallocateCodecOnIdle:Z

    iput-boolean v1, p0, LX/8CU;->disablePreallocateCodecDuringStartup:Z

    iput-boolean v1, p0, LX/8CU;->useNetworkAwareSettingsForUnstallBuffer:Z

    iput-boolean v1, p0, LX/8CU;->disableStoriesCustomizedUnstallBuffer:Z

    iput-boolean v1, p0, LX/8CU;->bgHeroServiceStatusUpdate:Z

    iput-boolean v1, p0, LX/8CU;->isExo2UseAbsolutePosition:Z

    iput-boolean v1, p0, LX/8CU;->shouldExcludeAbsolutePositionForClippingMediaSource:Z

    iput-boolean v1, p0, LX/8CU;->isExo2MediaCodecReuseEnabled:Z

    iput-boolean v1, p0, LX/8CU;->useBlockingSetSurfaceExo2:Z

    iput-boolean v1, p0, LX/8CU;->isExo2AggresiveMicrostallFixEnabled:Z

    iput-boolean v1, p0, LX/8CU;->warmupVp9Codec:Z

    iput-boolean v1, p0, LX/8CU;->warmupAv1Codec:Z

    iget-boolean v0, p1, LX/7OH;->A0h:Z

    iput-boolean v0, p0, LX/8CU;->playerRespawnExo2:Z

    iput-boolean v1, p0, LX/8CU;->updateLoadingPriorityExo2:Z

    iput-boolean v1, p0, LX/8CU;->checkReadToEndBeforeUpdatingFinalState:Z

    iput-boolean v1, p0, LX/8CU;->isExo2Vp9Enabled:Z

    iput-boolean v1, p0, LX/8CU;->exo2Vp9UseSurfaceRenderer:Z

    iput-boolean v1, p0, LX/8CU;->skipEvaluateIflastChunkWasInitialization:Z

    iput-boolean v1, p0, LX/8CU;->logOnApacheFallback:Z

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/8CU;->enableSystrace:Z

    iput-boolean v1, p0, LX/8CU;->isDefaultMC:Z

    const-string v0, "unset"

    iput-object v0, p0, LX/8CU;->mcDebugState:Ljava/lang/String;

    iput-object v0, p0, LX/8CU;->mcValueSource:Ljava/lang/String;

    iput-boolean v1, p0, LX/8CU;->enableCodecPreallocation:Z

    iput-boolean v1, p0, LX/8CU;->enableVp9CodecPreallocation:Z

    iput-boolean v1, p0, LX/8CU;->preventPreallocateIfNotEmpty:Z

    iput-boolean v1, p0, LX/8CU;->enableRequestEtdHeader:Z

    iput-boolean v1, p0, LX/8CU;->reportLastVideoInCrash:Z

    const-wide/16 v0, 0x0

    iput-wide v0, p0, LX/8CU;->maxDurationUsForFullSegmentPrefetch:J

    const/4 v1, 0x0

    iput-boolean v1, p0, LX/8CU;->isSetSerializableBlacklisted:Z

    iput-boolean v1, p0, LX/8CU;->useWatermarkEvaluatorForProgressive:Z

    iput-boolean v1, p0, LX/8CU;->useMaxBufferForProgressive:Z

    iget-boolean v0, p1, LX/7OH;->A0m:Z

    iput-boolean v0, p0, LX/8CU;->useDummySurfaceExo2:Z

    iput-boolean v1, p0, LX/8CU;->useVideoSourceAsWarmupKey:Z

    const-wide/32 v0, 0x5b8d80

    iput-wide v0, p0, LX/8CU;->maxBufferDurationPausedLiveUs:J

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->enableUsingASRCaptions:Z

    iput-boolean v0, p0, LX/8CU;->enableBitrateAwareAudioPrefetch:Z

    iput-boolean v0, p0, LX/8CU;->proxyDrmProvisioningRequests:Z

    iput-boolean v0, p0, LX/8CU;->liveUseLowPriRequests:Z

    const/16 v0, 0xfa0

    iput v0, p0, LX/8CU;->liveDashEdgeLatencyMs:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->logLatencyEvents:Z

    iput-boolean v0, p0, LX/8CU;->disableLatencyManagerOnStaticManifest:Z

    iput-boolean v0, p0, LX/8CU;->enablePreSeekToApi:Z

    iput-boolean v0, p0, LX/8CU;->continuouslyLoadFromPreSeekLocation:Z

    const-wide v0, 0x7fffffffffffffffL

    iput-wide v0, p0, LX/8CU;->minBufferForPreSeekMs:J

    const/4 v0, 0x0

    iput v0, p0, LX/8CU;->audioVideoSyncPeriodMs:I

    iput-boolean v0, p0, LX/8CU;->enableProgressivePrefetchWhenNoRepresentations:Z

    iput-boolean v0, p0, LX/8CU;->continueLoadingOnSeekbarExo2:Z

    iput-boolean v0, p0, LX/8CU;->subtitleDurationToMaxValue:Z

    iput-boolean v0, p0, LX/8CU;->isExo2DrmEnabled:Z

    iput-boolean v0, p0, LX/8CU;->enableDrmProvisioningRetry:Z

    iput-boolean v0, p0, LX/8CU;->sortSubripSubtitles:Z

    iput-boolean v0, p0, LX/8CU;->logStallOnPauseOnError:Z

    iput-boolean v0, p0, LX/8CU;->skipSynchronizedUpdatePriority:Z

    iput-boolean v0, p0, LX/8CU;->exo2ReuseManifestAfterInitialParse:Z

    iput-boolean v0, p0, LX/8CU;->enableFrameBasedLogging:Z

    const/16 v0, 0x64

    iput v0, p0, LX/8CU;->prefetchTaskQueueSize:I

    const/4 v0, 0x1

    iput v0, p0, LX/8CU;->prefetchTaskQueueWorkerNum:I

    const/4 v0, 0x2

    iput v0, p0, LX/8CU;->prefetchUrgentTaskQueueWorkerNum:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->usePrefetchSegmentOffset:Z

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/8CU;->refreshManifestAfterInit:Z

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->disableAudioFocusInGroot:Z

    iput-boolean v0, p0, LX/8CU;->offloadGrootAudioFocus:Z

    iput-boolean v0, p0, LX/8CU;->enableDeduplicateImfEmsgAtPlayer:Z

    const/16 v0, 0xfa0

    iput v0, p0, LX/8CU;->numMsToPrefetch:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->enableWifiLongerPrefetchAds:Z

    iput-boolean v0, p0, LX/8CU;->enableAllLongerPrefetchAds:Z

    const/4 v0, -0x1

    iput v0, p0, LX/8CU;->maxWifiPrefetchDurationMsAds:I

    const/4 v0, 0x0

    iput v0, p0, LX/8CU;->adBreakEnahncedPrefetchDurationMs:I

    iput-boolean v0, p0, LX/8CU;->enableAdBreakEnhancedPrefetch:Z

    const/high16 v0, 0x100000

    iput v0, p0, LX/8CU;->maxWifiBytesToPrefetchAds:I

    const/4 v0, -0x1

    iput v0, p0, LX/8CU;->minLiveStartPositionMs:I

    const/4 v0, 0x0

    iput v0, p0, LX/8CU;->stopRefreshingManifestNoPlaybackUpdateAfterTimeMs:I

    const/16 v0, 0x2ee0

    iput v0, p0, LX/8CU;->liveDashHighWatermarkMs:I

    const/4 v0, 0x0

    iput v0, p0, LX/8CU;->liveDashLowWatermarkMs:I

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/8CU;->prefetchTaskQueuePutInFront:Z

    iput v0, p0, LX/8CU;->prefetchTaskQueueRetryNumber:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->enableCancelOngoingRequestPause:Z

    iput-boolean v0, p0, LX/8CU;->shouldPrefetchSecondSegmentOffset:Z

    iput-boolean v0, p0, LX/8CU;->fallbackToFirstSegment:Z

    iput-boolean v0, p0, LX/8CU;->enableSegmentIndexCheckForPrefetchBytes:Z

    iput-boolean v0, p0, LX/8CU;->validateBytesToFallbackOnFirstSegment:Z

    const-string v2, ""

    iput-object v2, p0, LX/8CU;->prefetchTagBlockList:Ljava/lang/String;

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/8CU;->enabledViewManagementInGroot:Z

    const/high16 v0, 0x20000

    iput v0, p0, LX/8CU;->maxBytesToPrefetchVOD:I

    const/high16 v0, 0x10000

    iput v0, p0, LX/8CU;->maxBytesToPrefetchCellVOD:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->enableLiveOneTimeLoadingJump:Z

    iput-boolean v0, p0, LX/8CU;->enableSpatialOpusRendererExo2:Z

    iput-boolean v0, p0, LX/8CU;->manifestErrorReportingExo2:Z

    iput-boolean v0, p0, LX/8CU;->manifestMisalignmentReportingExo2:Z

    iput-boolean v0, p0, LX/8CU;->enableVideoHybridCache:Z

    iput-boolean v0, p0, LX/8CU;->enableHybridCacheForPrefetch:Z

    iput-boolean v0, p0, LX/8CU;->enableVideoMemoryCache:Z

    const v0, 0x18aa0

    iput v0, p0, LX/8CU;->videoMemoryCacheSizeKb:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->alwaysPerformContentLengthUpdateFirst:Z

    iput-boolean v0, p0, LX/8CU;->enableUpdateProgressiveContentLengthFromCache:Z

    iput-boolean v0, p0, LX/8CU;->enableLongCacheKeyForContentLength:Z

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/8CU;->updateParamOnGetManifestFetcher:Z

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->prefetchBypassFilter:Z

    iput-boolean v0, p0, LX/8CU;->useBufferBasedAbrPDash:Z

    const/4 v0, 0x5

    iput v0, p0, LX/8CU;->minimumLogLevel:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->isMeDevice:Z

    iput-boolean v0, p0, LX/8CU;->enableOffloadingIPC:Z

    iput-boolean v0, p0, LX/8CU;->pausePlayingVideoWhenRelease:Z

    iput-boolean v0, p0, LX/8CU;->enableAv1Dav1d:Z

    iput-boolean v0, p0, LX/8CU;->enableAv1LibGav1:Z

    iput-boolean v0, p0, LX/8CU;->prioritizeAv1HardwareDecoder:Z

    iget-object v0, p1, LX/7OH;->A0V:Ljava/util/HashMap;

    iput-object v0, p0, LX/8CU;->blockListedHardwareDecoderMap:Ljava/util/HashMap;

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/8CU;->prioritizeAv1Dav1dOverLibgav1:Z

    iput v0, p0, LX/8CU;->dav1dThreads:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->handleReleasedReusedSurfaceTexture:Z

    const/4 v0, 0x1

    iput v0, p0, LX/8CU;->dav1dMaxFrameDelay:I

    iput-boolean v0, p0, LX/8CU;->dav1dApplyGrain:Z

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->av1SetBuffersDataspace:Z

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/8CU;->av1UseMemoryCleanupFixes:Z

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->av1UseDav1dSynchronizationFixes:Z

    iput-boolean v0, p0, LX/8CU;->av1FlushDav1dProperly:Z

    iput-boolean v0, p0, LX/8CU;->useForceSurfaceChange:Z

    iput-boolean v0, p0, LX/8CU;->parseAndAttachETagManifest:Z

    iput-boolean v0, p0, LX/8CU;->enableSecondPhasePrefetch:Z

    iput-boolean v0, p0, LX/8CU;->disableSecondPhasePrefetchForReels:Z

    iput-boolean v0, p0, LX/8CU;->disableSecondPhasePrefetchForDataSaver:Z

    iput-boolean v0, p0, LX/8CU;->enableSecondPhasePrefetchWebm:Z

    iput-boolean v0, p0, LX/8CU;->disableSecondPhasePrefetchOnAppScrolling:Z

    iput-boolean v0, p0, LX/8CU;->enableSecondPhaseAlignment:Z

    iput v0, p0, LX/8CU;->secondPhasePrefetchQueueMaxSize:I

    iput v0, p0, LX/8CU;->numSegmentsToSecondPhasePrefetch:I

    iput v0, p0, LX/8CU;->numSegmentsToSecondPhasePrefetchAudio:I

    iput v0, p0, LX/8CU;->numSegmentsToSecondPhasePrefetchXHEAACAudio:I

    iput-boolean v0, p0, LX/8CU;->enableLogSemiCachedEvents:Z

    iput-boolean v0, p0, LX/8CU;->enableCacheBlockWithoutTimeout:Z

    iput-boolean v0, p0, LX/8CU;->enableLogExceptionMessageOnError:Z

    iput-boolean v0, p0, LX/8CU;->reportExceptionsAsSoftErrors:Z

    iput-boolean v0, p0, LX/8CU;->reportExceptionAsMME:Z

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/8CU;->checkCachedLockedCacheSpan:Z

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->prefetchAudioFirst:Z

    iput-boolean v0, p0, LX/8CU;->cancelOngoingRequest:Z

    iput-boolean v0, p0, LX/8CU;->enableCancelPrefetchInQueuePrepare:Z

    iput-boolean v0, p0, LX/8CU;->enableBoostOngoingPrefetchPriorityPrepare:Z

    iput-boolean v0, p0, LX/8CU;->enableBoostOngoingPrefetchPriorityPlay:Z

    iput-boolean v0, p0, LX/8CU;->enableDemoteOngoingPrefetchPriorityPause:Z

    iput-boolean v0, p0, LX/8CU;->enableCancelOngoingPrefetchPause:Z

    iput-boolean v0, p0, LX/8CU;->enableCancelFollowupPrefetch:Z

    iput-boolean v0, p0, LX/8CU;->prefetchAudioFirstForStoriesAds:Z

    iput-boolean v0, p0, LX/8CU;->skipAudioPrefetch:Z

    iput-boolean v0, p0, LX/8CU;->allowOutOfBoundsAccessForPDash:Z

    iput v0, p0, LX/8CU;->minNumManifestForOutOfBoundsPDash:I

    iput-boolean v0, p0, LX/8CU;->enableNeedCenteringIndependentlyGroot:Z

    iput-boolean v0, p0, LX/8CU;->av1ThrowExceptionOnPictureError:Z

    iput-boolean v0, p0, LX/8CU;->av1ThrowExceptionOnNonDav1dDecoder:Z

    iget-wide v0, p1, LX/7OH;->A0F:J

    iput-wide v0, p0, LX/8CU;->ignoreStreamErrorsTimeoutMs:J

    const-wide/16 v0, 0x0

    iput-wide v0, p0, LX/8CU;->ignoreLiveStreamErrorsTimeoutMs:J

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->callbackFirstCaughtStreamError:Z

    iput-boolean v0, p0, LX/8CU;->avoidSecondPhaseOnCell:Z

    iput-boolean v0, p0, LX/8CU;->includeLiveTraceHeader:Z

    iput-boolean v0, p0, LX/8CU;->alwaysReuseManifestFetcher:Z

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/8CU;->av1Dav1dEnableVpsLogging:Z

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->av1Dav1dUseSurfaceViewSetFix:Z

    iput-boolean v0, p0, LX/8CU;->skipSurfaceViewReparentOnSetCurrentView:Z

    iput-boolean v0, p0, LX/8CU;->skipSurfaceViewTransactionOnSameSurface:Z

    iput-boolean v0, p0, LX/8CU;->allowMultiPlayerFormatWarmup:Z

    iput-boolean v0, p0, LX/8CU;->reorderSeekPrepare:Z

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/8CU;->prioritizeTimeOverSizeThresholds:Z

    iput-boolean v0, p0, LX/8CU;->livePrioritizeTimeOverSizeThresholds:Z

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->disableCapBufferSizeLocalProgressive:Z

    iput-boolean v0, p0, LX/8CU;->useHeroBufferSize:Z

    iput v0, p0, LX/8CU;->videoBufferSize:I

    iput v0, p0, LX/8CU;->audioBufferSize:I

    iput-boolean v0, p0, LX/8CU;->enableMemoryAwareBufferSizeUsingRed:Z

    iput-boolean v0, p0, LX/8CU;->enableMemoryAwareBufferSizeUsingYellow:Z

    const-wide/high16 v0, 0x3ff0000000000000L    # 1.0

    iput-wide v0, p0, LX/8CU;->redMemoryBufferSizeMultiplier:D

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->useAccumulatorForBw:Z

    iput-boolean v0, p0, LX/8CU;->parseManifestIdentifier:Z

    iput-boolean v0, p0, LX/8CU;->enableCDNDebugHeaders:Z

    const/4 v0, -0x1

    iput v0, p0, LX/8CU;->maxTimeMsSinceRefreshPDash:I

    const/4 v0, 0x0

    iput v0, p0, LX/8CU;->predictionMaxSegmentDurationMs:I

    const/16 v0, 0x2134

    iput v0, p0, LX/8CU;->predictiveDashReadTimeoutMs:I

    const/4 v0, 0x0

    iput v0, p0, LX/8CU;->segDurationMultiplier:I

    const/16 v0, 0x1f40

    iput v0, p0, LX/8CU;->predictedHuddleDashManifestReadTimeoutMs:I

    iput v0, p0, LX/8CU;->predictedLiveDashManifestReadTimeoutMs:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->enableServerSideAbr:Z

    iput-boolean v0, p0, LX/8CU;->enableServerSideForwardBwe:Z

    iput-boolean v0, p0, LX/8CU;->useSSAbrBWE:Z

    iput-boolean v0, p0, LX/8CU;->useSSAbrMinRtt:Z

    iput-boolean v0, p0, LX/8CU;->useSsBweForVod:Z

    iput-boolean v0, p0, LX/8CU;->enableSsBweHeaderForLive:Z

    iput-boolean v0, p0, LX/8CU;->shareBWEEstimateAcrossVideos:Z

    iput-boolean v0, p0, LX/8CU;->splitBweOnRadio:Z

    const v0, 0x7a120

    iput v0, p0, LX/8CU;->progressivePrefetchBytesWifi:I

    const v0, 0x3e800

    iput v0, p0, LX/8CU;->progressivePrefetchBytesCell:I

    const/4 v0, 0x0

    iput v0, p0, LX/8CU;->maxSegmentsToPredict:I

    iput-boolean v0, p0, LX/8CU;->getMinLoadPositionStartOfPlayback:Z

    const v0, 0x3f4ccccd    # 0.8f

    iput v0, p0, LX/8CU;->largeJumpBandwidthMultiplier:F

    const/high16 v0, 0x3f800000    # 1.0f

    iput v0, p0, LX/8CU;->smallJumpBandwidthMultiplier:F

    const/16 v0, 0x7d0

    iput v0, p0, LX/8CU;->highJumpDistanceMs:I

    const/16 v0, 0x1f40

    iput v0, p0, LX/8CU;->lowJumpDistanceMs:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->enableDynamicDiscontinuityDistance:Z

    const/16 v0, 0xfa0

    iput v0, p0, LX/8CU;->dynamicDiscontinuityInitialPosMs:I

    const/4 v0, 0x3

    iput v0, p0, LX/8CU;->maxStaleManifestCountForDiscontinuityJumps:I

    const/16 v0, 0x7d0

    iput v0, p0, LX/8CU;->minTimeBetweenDynamicCursorChangesMs:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->enableDynamicCursorDistance:Z

    const/16 v0, 0x7d0

    iput v0, p0, LX/8CU;->largeBandwidthCursorMs:I

    const/16 v0, 0xfa0

    iput v0, p0, LX/8CU;->smallBandwidthCursorMs:I

    const/16 v0, 0x1770

    iput v0, p0, LX/8CU;->largeBandwidthToleranceMs:I

    iput v0, p0, LX/8CU;->smallBandwidthToleranceMs:I

    const/16 v0, 0x3c

    iput v0, p0, LX/8CU;->minimumTimeBetweenStallsS:I

    const/16 v0, 0x1e

    iput v0, p0, LX/8CU;->minimumTimeBetweenSpeedChangesS:I

    const/4 v0, 0x5

    iput v0, p0, LX/8CU;->minTimeBetweenStallToIgnoreDiscontJumpS:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->ignoreTemplatedMinLoadPosition:Z

    iput-boolean v0, p0, LX/8CU;->preventJumpStaticManifest:Z

    iput-boolean v0, p0, LX/8CU;->maybeSkipInlineManifestForLSB:Z

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/8CU;->disableSkipInlineForHuddle:Z

    const/16 v0, 0x4b

    iput v0, p0, LX/8CU;->skipInlineManifestForLsbConfPercentile:I

    const/high16 v0, 0x3f800000    # 1.0f

    iput v0, p0, LX/8CU;->bandwidthMultiplierToSkipPrefetchedContent:F

    const/4 v0, 0x0

    iput v0, p0, LX/8CU;->maxTimeToSkipInlineManifestMs:I

    iput v0, p0, LX/8CU;->minTimeToSkipInlineManifestMs:I

    const-wide/16 v0, 0x0

    iput-wide v0, p0, LX/8CU;->aggressiveEdgeLatencyOverrideForLSB:J

    const/16 v0, 0x4b

    iput v0, p0, LX/8CU;->aggressiveEdgeLatencyForLsbConfPercentile:I

    const/high16 v0, 0x3f000000    # 0.5f

    iput v0, p0, LX/8CU;->bandwidthMultiplierForAggressiveEdgeLatency:F

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->enableLatencyPlaybackSpeed:Z

    iput-boolean v0, p0, LX/8CU;->useSimpleSpeedController:Z

    iput-boolean v0, p0, LX/8CU;->useSteadyStateToControlSpeed:Z

    const v0, 0x3f866666    # 1.05f

    iput v0, p0, LX/8CU;->expBackOffSpeedUp:F

    const/high16 v0, -0x40800000    # -1.0f

    iput v0, p0, LX/8CU;->watchTimeThresholdToDisableFollowupPrefetch:F

    const/high16 v0, 0x3f000000    # 0.5f

    iput v0, p0, LX/8CU;->pidMultiplierFloor:F

    const v0, 0x3f99999a    # 1.2f

    iput v0, p0, LX/8CU;->pidParameterMultiplierInitial:F

    const v0, 0x3f733333    # 0.95f

    iput v0, p0, LX/8CU;->pidParameterExpBackOff:F

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->enableLiveLatencyManager:Z

    iput-boolean v0, p0, LX/8CU;->enableLiveJumpByTrimBuffer:Z

    iput-boolean v0, p0, LX/8CU;->enableLatencyManagerRateLimiting:Z

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/8CU;->forceSeekRushPlayback:Z

    iput-object v2, p0, LX/8CU;->liveLatencyManagerPlayerFormat:Ljava/lang/String;

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->enableLiveBufferMeter:Z

    iput-boolean v0, p0, LX/8CU;->enableLiveBWEstimation:Z

    const/16 v0, 0x3e8

    iput v0, p0, LX/8CU;->liveTrimByBufferMeterMinDeltaMs:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->enableAvc1ColorConfigParseFix:Z

    const/16 v0, 0x14

    iput v0, p0, LX/8CU;->liveBufferDurationFluctuationTolerancePercent:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->liveBufferMeterTrimByMinBuffer:Z

    iput-boolean v0, p0, LX/8CU;->enableSuspensionAfterBroadcasterStall:Z

    iput-boolean v0, p0, LX/8CU;->allowImmediateLiveBufferTrim:Z

    const/16 v0, 0x1388

    iput v0, p0, LX/8CU;->initialBufferTrimPeriodMs:I

    const/16 v0, 0x1770

    iput v0, p0, LX/8CU;->initialBufferTrimThresholdMs:I

    const/16 v0, 0xfa0

    iput v0, p0, LX/8CU;->initialBufferTrimTargetMs:I

    iput v0, p0, LX/8CU;->extendedLiveRebufferThresholdMs:I

    iput v0, p0, LX/8CU;->allowedExtendedRebufferPeriodMs:I

    const/16 v0, 0x7530

    iput v0, p0, LX/8CU;->frequentBroadcasterStallIntervalThresholdMs:I

    const/16 v0, 0x1770

    iput v0, p0, LX/8CU;->extendedPremiumTierLiveRebufferThresholdMs:I

    const/16 v0, 0x2710

    iput v0, p0, LX/8CU;->allowedExtendedPremiumTierRebufferPeriodMs:I

    const v0, 0xea60

    iput v0, p0, LX/8CU;->frequentPremiumTierBroadcasterStallIntervalThresholdMs:I

    const/16 v0, 0x1770

    iput v0, p0, LX/8CU;->extendedApiTierLiveRebufferThresholdMs:I

    const v0, 0xea60

    iput v0, p0, LX/8CU;->frequentApiTierBroadcasterStallIntervalThresholdMs:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->enableLiveTierSpecificRebuffer:Z

    iput-boolean v0, p0, LX/8CU;->enableMP3Extractor:Z

    iput-boolean v0, p0, LX/8CU;->enableMp3Mp4ExtractorLogic:Z

    const/4 v0, -0x1

    iput v0, p0, LX/8CU;->maxNumRedirects:I

    const-string v0, "FB4A/Facebook"

    iput-object v0, p0, LX/8CU;->defaultUserAgent:Ljava/lang/String;

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->splitLastSegmentCachekey:Z

    iput-boolean v0, p0, LX/8CU;->enableEmsgPtsAlignment:Z

    const/4 v0, 0x1

    iput v0, p0, LX/8CU;->fragmentedMp4ExtractorVersion:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->enablePlayerActionStateLoggingInFlytrap:Z

    iput-boolean v0, p0, LX/8CU;->enableWarmUpRequestOffscreen:Z

    iput-boolean v0, p0, LX/8CU;->enableFirstWarmUpRequestOnScreen:Z

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/8CU;->newDownstreamFormatChange:Z

    const/4 v0, 0x0

    iput v0, p0, LX/8CU;->microStallThresholdMsToUseMinBuffer:I

    iput-boolean v0, p0, LX/8CU;->updateUnstallBufferDuringPlayback:Z

    iput-boolean v0, p0, LX/8CU;->updateConcatMsDuringPlayback:Z

    iput-boolean v0, p0, LX/8CU;->enableVodDrmPrefetch:Z

    iput-boolean v0, p0, LX/8CU;->enableActiveDrmSessionStoreRelease:Z

    const/4 v0, 0x3

    iput v0, p0, LX/8CU;->drmSessionStoreCapacity:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->enableCustomizedXHEAACConfig:Z

    iput-boolean v0, p0, LX/8CU;->enableSeamlessAudioCodecAdaptation:Z

    iput-boolean v0, p0, LX/8CU;->enableCustomizedDRCEffect:Z

    iput-boolean v0, p0, LX/8CU;->enableCustomizedDRCForHeadset:Z

    const/16 v0, 0x12

    iput v0, p0, LX/8CU;->lateNightHourLowerThreshold:I

    const/4 v0, 0x6

    iput v0, p0, LX/8CU;->lateNightHourUpperThreshold:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->enableAsynchronousBufferQueueing:Z

    iput-boolean v0, p0, LX/8CU;->enableSynchronizeCodecInteractionsWithQueueing:Z

    iput-boolean v0, p0, LX/8CU;->enableLowLatencyDecoding:Z

    iput-boolean v0, p0, LX/8CU;->enableLowLatencyDecodingOverrideSDKGating:Z

    const/16 v0, 0x40

    iput v0, p0, LX/8CU;->xHEAACTargetReferenceLvl:I

    const/4 v0, 0x3

    iput v0, p0, LX/8CU;->xHEAACCEffectType:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->useBwBpsForConnectionQuality:Z

    iput-boolean v0, p0, LX/8CU;->preventWarmupInvalidSource:Z

    iput-boolean v0, p0, LX/8CU;->reportUnexpectedStopLoading:Z

    iput-boolean v0, p0, LX/8CU;->enableReduceRetryBeforePlay:Z

    const/4 v0, 0x1

    iput v0, p0, LX/8CU;->minRetryCountBeforePlay:I

    const/4 v1, 0x0

    iput-boolean v1, p0, LX/8CU;->forceMinWatermarkGreaterThanMinRebuffer:Z

    iput-boolean v1, p0, LX/8CU;->bypassGreaterThanMinRebufferWhenBeforePlay:Z

    iput-boolean v1, p0, LX/8CU;->useMaxOfLowWatermarkOrPrevHighWaterMarkWhenForced:Z

    iput-boolean v1, p0, LX/8CU;->useWifiMaxWaterMarkMsConfig:Z

    iput-boolean v1, p0, LX/8CU;->useCellMaxWaterMarkMsConfig:Z

    iput-boolean v1, p0, LX/8CU;->useNetworkAwaretPrefetchTaskQueueWorkerNum:Z

    const/4 v0, 0x0

    iput-object v0, p0, LX/8CU;->wifiMaxWatermarkMsConfig:LX/8CA;

    iput-object v0, p0, LX/8CU;->cellMaxWatermarkMsConfig:LX/8CA;

    iput-object v0, p0, LX/8CU;->networkAwareDisableSecondPhasePrefetch:LX/8CA;

    iput-object v0, p0, LX/8CU;->networkAwarePrefetchTaskQueueWorkerNum:LX/8CA;

    iput-object v0, p0, LX/8CU;->networkAwareHttpPriorityIncrementalForStreaming:LX/8CA;

    iput-boolean v1, p0, LX/8CU;->skipInvalidSamples:Z

    iput v1, p0, LX/8CU;->minBufferedDurationMsToCancel:I

    iput v1, p0, LX/8CU;->decoderInitializationRetryTimeMs:I

    iput v1, p0, LX/8CU;->decoderDequeueRetryTimeMs:I

    iput v1, p0, LX/8CU;->renderRetryTimeMs:I

    iput-boolean v1, p0, LX/8CU;->disableRecoverInBackground:Z

    iput-boolean v1, p0, LX/8CU;->enableEnsureBindService:Z

    iput-boolean v1, p0, LX/8CU;->enableFallbackToMainProcess:Z

    iput-boolean v1, p0, LX/8CU;->enableKillProcessBeforeRebind:Z

    iput v1, p0, LX/8CU;->restartServiceThresholdMs:I

    iput-boolean v1, p0, LX/8CU;->fixSurfaceInvisibleParent:Z

    iput v1, p0, LX/8CU;->depthTocheckSurfaceInvisibleParent:I

    iput-boolean v1, p0, LX/8CU;->isAudioDataSummaryEnabled:Z

    iput-boolean v1, p0, LX/8CU;->enableBlackscreenDetector:Z

    const-wide/16 v0, 0x7d0

    iput-wide v0, p0, LX/8CU;->blackscreenSampleIntervalMs:J

    const-wide/16 v0, 0x3e8

    iput-wide v0, p0, LX/8CU;->blackscreenNoSampleThresholdMs:J

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->blackscreenDetectOnce:Z

    iput-boolean v0, p0, LX/8CU;->fixBlackscreenByRecreatingSurface:Z

    iput-boolean v0, p0, LX/8CU;->removeGifPrefixForDRMKeyRequest:Z

    iput-boolean v0, p0, LX/8CU;->enableDrmSessionStore:Z

    iput-boolean v0, p0, LX/8CU;->skipMediaCodecStopOnRelease:Z

    iget-object v0, p1, LX/7OH;->A0a:Ljava/util/Set;

    iput-object v0, p0, LX/8CU;->softErrorErrorDomainBlacklist:Ljava/util/Set;

    iget-object v0, p1, LX/7OH;->A0Z:Ljava/util/Set;

    iput-object v0, p0, LX/8CU;->softErrorErrorCodeBlacklist:Ljava/util/Set;

    iget-object v0, p1, LX/7OH;->A0b:Ljava/util/Set;

    iput-object v0, p0, LX/8CU;->softErrorErrorMessageBlacklist:Ljava/util/Set;

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->logPausedSeekPositionBeforeSettingState:Z

    iput-boolean v0, p0, LX/8CU;->enableRetryWarmup:Z

    const/16 v0, 0x64

    iput v0, p0, LX/8CU;->initChunkCacheSize:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->skipAudioMediaCodecStopOnRelease:Z

    iput-boolean v0, p0, LX/8CU;->enableCodecDeadlockFix:Z

    iget v0, p1, LX/7OH;->A04:I

    iput v0, p0, LX/8CU;->frequentStallIntervalThresholdMs:I

    iget v0, p1, LX/7OH;->A0D:I

    iput v0, p0, LX/8CU;->stallCountsToUpdateDynamicRebufferThreshold:I

    iget v0, p1, LX/7OH;->A03:I

    iput v0, p0, LX/8CU;->extendedMinRebufferThresholdMs:I

    const/16 v0, 0xfa0

    iput v0, p0, LX/8CU;->allowedExtendedMinRebuffePeriodMs:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->fixXmlParserError:Z

    const/4 v0, -0x1

    iput v0, p0, LX/8CU;->globalStallCountsToUpdateDynamicRebuffer:I

    iput v0, p0, LX/8CU;->globalStallCountsToUpdateLiveDynamicRebuffer:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->enableEvictPlayerOnAudioTrackInitFailed:Z

    iput-boolean v0, p0, LX/8CU;->enableCheckAudioError:Z

    const/4 v0, 0x3

    iput v0, p0, LX/8CU;->maxRetryCountByEvictPlayerOnAudioTrackInitFailed:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->enableEvictCacheOnExoplayerErrors:Z

    const/4 v0, 0x1

    iput v0, p0, LX/8CU;->maxRetryCountByEvictCacheOnExoplayerErrors:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->disableAudioRendererOnAudioTrackInitFailed:Z

    const/4 v0, 0x3

    iput v0, p0, LX/8CU;->audioTrackInitFailedFallbackApplyThreshold:I

    const-wide/32 v0, 0x493e0

    iput-wide v0, p0, LX/8CU;->killVideoProcessOnExoPlaybackExceptionRetryTimeMs:J

    const/4 v0, 0x3

    iput v0, p0, LX/8CU;->killVideoProcessOnExoPlaybackExceptionMaximumRetryCount:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->enableKillVideoProcessForAudioTrackInitFailed:Z

    iput-boolean v0, p0, LX/8CU;->enableKillVideoProcessForIllegalStateException:Z

    iput-boolean v0, p0, LX/8CU;->enableRebootDeviceErrorUIForAudioTrackInitFailed:Z

    iput-boolean v0, p0, LX/8CU;->enableRebootDeviceErrorUIForCodecInitFailed:Z

    iput-boolean v0, p0, LX/8CU;->enableRebootDeviceErrorUIForIllegalStateException:Z

    iput-boolean v0, p0, LX/8CU;->useThreadSafeStandaloneClock:Z

    iput-boolean v0, p0, LX/8CU;->useMultiPeriodBufferCalculation:Z

    iput-boolean v0, p0, LX/8CU;->isVideoQplPipelineEnabled:Z

    iput-boolean v0, p0, LX/8CU;->disableIsCachedApi:Z

    iput-boolean v0, p0, LX/8CU;->enableLoadErrorHandlingPolicy:Z

    iput-boolean v0, p0, LX/8CU;->enableBlockListingResource:Z

    iput-boolean v0, p0, LX/8CU;->enable500R1FallbackLogging:Z

    iput-boolean v0, p0, LX/8CU;->checkManifestRepresentationFormatMismatch:Z

    iput-boolean v0, p0, LX/8CU;->checkLiveSourceUri:Z

    iput-object v2, p0, LX/8CU;->oneSemanticsOsParamValue:Ljava/lang/String;

    iput-boolean v0, p0, LX/8CU;->forceOneSemanticsHandling:Z

    iput v0, p0, LX/8CU;->forceOneSemanticsWaveHandling:I

    iput v0, p0, LX/8CU;->expBackoffInRetryBaseDelay:I

    iput-boolean v0, p0, LX/8CU;->shouldLoadBinaryDataFromManifest:Z

    iput-boolean v0, p0, LX/8CU;->enhanceParseException:Z

    iput-boolean v0, p0, LX/8CU;->smartGcEnabled:Z

    iput v0, p0, LX/8CU;->smartGcTimeout:I

    iput-boolean v0, p0, LX/8CU;->getPlaybackPrefFromPrefetchRequest:Z

    iput-boolean v0, p0, LX/8CU;->useShortKey:Z

    const/4 v0, 0x3

    iput v0, p0, LX/8CU;->staleManifestThreshold:I

    iput v0, p0, LX/8CU;->staleManifestThresholdToShowInterruptUI:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->checkThumbnailCache:Z

    iput-boolean v0, p0, LX/8CU;->ignore404AfterStreamEnd:Z

    iput-boolean v0, p0, LX/8CU;->allowPredictiveAlignment:Z

    iput-boolean v0, p0, LX/8CU;->enableUnifiedGrootErrorHandling:Z

    iput v0, p0, LX/8CU;->minScoreThresholdForLL:I

    iput v0, p0, LX/8CU;->goodVsrScoreThreshold:I

    iput v0, p0, LX/8CU;->maxTrackJumpsAllowed:I

    const/4 v0, -0x1

    iput v0, p0, LX/8CU;->maxDistanceBetweenTracksMs:I

    iput v0, p0, LX/8CU;->maxPastOtherTrackDistanceMs:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->enableVideoDebugEventLogging:Z

    iput-boolean v0, p0, LX/8CU;->respectDroppedQualityFlag:Z

    iput-object v2, p0, LX/8CU;->ssAbrExperimentSetting:Ljava/lang/String;

    const/4 v0, 0x0

    iput v0, p0, LX/8CU;->ssAbrAlphaDecay:F

    const/4 v0, 0x0

    iput v0, p0, LX/8CU;->ssAbrNumSamplesAvg:I

    iput v0, p0, LX/8CU;->ssAbrMinSamples:I

    iput-boolean v0, p0, LX/8CU;->enableJumpTrackFallingBehind:Z

    iput-boolean v0, p0, LX/8CU;->enable404SegmentRemapping:Z

    iput-boolean v0, p0, LX/8CU;->enableOneSemanticsLoaderRetry:Z

    iput-boolean v0, p0, LX/8CU;->enable204SegmentRemapping:Z

    const/4 v0, 0x3

    iput v0, p0, LX/8CU;->maxPredictedSegmentsToRemap:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->skipThumbnailCacheKey:Z

    iput-boolean v0, p0, LX/8CU;->enableCreateByteBufferFromABufferNullCheckHooks:Z

    iput-boolean v0, p0, LX/8CU;->enableBusySignalToFramework:Z

    iput-boolean v0, p0, LX/8CU;->shouldWarmupAwareOfAppScrolling:Z

    iput-boolean v0, p0, LX/8CU;->shouldUseWarmupSlot:Z

    iput-boolean v0, p0, LX/8CU;->enableDelayWarmupRunning:Z

    const/16 v0, 0x3e8

    iput v0, p0, LX/8CU;->delayWarmupRunningMs:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->enableWarmupProcessPeriodically:Z

    iput-boolean v0, p0, LX/8CU;->enableStopWarmupSchedulerEmpty:Z

    iput-boolean v0, p0, LX/8CU;->enableFillBufferHooks:Z

    iput-boolean v0, p0, LX/8CU;->enableFreeNodeHooks:Z

    iput-boolean v0, p0, LX/8CU;->enableOnMessageReceivedHooks:Z

    iput-boolean v0, p0, LX/8CU;->enableSendCommandHooks:Z

    iput-boolean v0, p0, LX/8CU;->enableOnOMXEmptyBufferDoneHooks:Z

    iput-boolean v0, p0, LX/8CU;->enableFillFreeBufferCheckNodeHooks:Z

    iput-boolean v0, p0, LX/8CU;->enableFixRemovePlayerViewFromParent:Z

    iput-boolean v0, p0, LX/8CU;->latencyControllerBypassLimits:Z

    const/high16 v0, 0x3f800000    # 1.0f

    iput v0, p0, LX/8CU;->targetBufferBytesFactor:F

    const/4 v1, 0x0

    iput-boolean v1, p0, LX/8CU;->enableOverrideBufferWatermark:Z

    iput-boolean v1, p0, LX/8CU;->enableOverrideEndPosition:Z

    iget-object v0, p1, LX/7OH;->A0P:LX/8CB;

    iput-object v0, p0, LX/8CU;->loggerSDKConfig:LX/8CB;

    iput-boolean v1, p0, LX/8CU;->enableMp4MultiTrafBoxesFix:Z

    const/4 v0, 0x5

    iput v0, p0, LX/8CU;->chunkSourceRetryMaximum:I

    iget-object v0, p1, LX/7OH;->A0W:Ljava/util/Map;

    iput-object v0, p0, LX/8CU;->liveLatencySettings:Ljava/util/Map;

    iput-boolean v1, p0, LX/8CU;->forceDisableULL:Z

    iput v1, p0, LX/8CU;->bufferDecreaseTimeMs:I

    iput v1, p0, LX/8CU;->scalingBufferErrorMs:I

    const/16 v0, 0xc8

    iput v0, p0, LX/8CU;->timeBetweenPIDSamplesMs:I

    iput v0, p0, LX/8CU;->adjustSpeedBottomThresholdMs:I

    const/16 v0, 0x32

    iput v0, p0, LX/8CU;->desiredBufferAcceptableErrorMs:I

    iput-boolean v1, p0, LX/8CU;->disableSpeedAdjustmentOnBadUserExperience:Z

    const/16 v0, 0x12c

    iput v0, p0, LX/8CU;->adjustSpeedTopThresholdMs:I

    iput-boolean v1, p0, LX/8CU;->enableRetryErrorLoggingInCancel:Z

    iput-boolean v1, p0, LX/8CU;->enableRetryOnConnection:Z

    iput-boolean v1, p0, LX/8CU;->enableLoaderRetryLoggingForManifest:Z

    iput-boolean v1, p0, LX/8CU;->enableLoaderRetryLoggingForMedia:Z

    iput-boolean v1, p0, LX/8CU;->enableContinueLoadingLoggingForManifest:Z

    iput-boolean v1, p0, LX/8CU;->enableContinueLoadingLoggingForMedia:Z

    iput-boolean v1, p0, LX/8CU;->disableLoadingRetryOnFatalError:Z

    const/4 v0, 0x1

    iput v0, p0, LX/8CU;->errorRecoveryAttemptRepeatCountFlushThreshold:I

    iput-boolean v1, p0, LX/8CU;->disableNetworkErrorCountInChunkSource:Z

    iput-boolean v1, p0, LX/8CU;->ignoreEmptyProfileLevels:Z

    iput-boolean v1, p0, LX/8CU;->exceedRendererCapabilitiesIfAllFilteredOut:Z

    iput-boolean v1, p0, LX/8CU;->alwaysPrefetchInBgDefaultPriorityThread:Z

    iput-boolean v1, p0, LX/8CU;->alwaysPrefetchInIdleExecutor:Z

    iput-boolean v1, p0, LX/8CU;->enableCustomizedPrefetchThreadPriority:Z

    iput v1, p0, LX/8CU;->customizedPrefetchThreadPriority:I

    iput-boolean v0, p0, LX/8CU;->postStoriesGrootPrefetchToHeroManagerThread:Z

    iput-boolean v0, p0, LX/8CU;->cleanUpHeartbeatMessagesIfNotPlaying:Z

    iput-boolean v0, p0, LX/8CU;->cleanUpHeartbeatMessagesOnStall:Z

    iput-boolean v0, p0, LX/8CU;->cleanUpHeartbeatMessagesOnPause:Z

    iget-boolean v0, p1, LX/7OH;->A0f:Z

    iput-boolean v0, p0, LX/8CU;->enableDynamicMinRebufferMsController:Z

    iput-boolean v1, p0, LX/8CU;->enableGlobalStallMonitor:Z

    iput-boolean v1, p0, LX/8CU;->enableGlobalNetworkMonitor:Z

    iput-boolean v1, p0, LX/8CU;->enableLiveTierSpecificBufferSetting:Z

    const/4 v0, -0x1

    iput v0, p0, LX/8CU;->liveMinRetryCounts:I

    const/4 v0, 0x5

    iput v0, p0, LX/8CU;->prefetchThreadUpdatedPriority:I

    iput-boolean v1, p0, LX/8CU;->changeThreadPriorityForPrefetch:Z

    const/4 v0, -0x1

    iput v0, p0, LX/8CU;->numOfBytesBeforeLoaderThreadSleep:I

    iput-boolean v1, p0, LX/8CU;->enableLiveBroadcastErrorUI:Z

    iput-boolean v1, p0, LX/8CU;->enableFixTrackIndexOOB:Z

    iput-boolean v1, p0, LX/8CU;->shouldAlwaysDo503Retry:Z

    iput v0, p0, LX/8CU;->retryCountsForStartPlayManifestFetch:I

    iput v0, p0, LX/8CU;->retryCountsForStartPlayManifest503:I

    iput-boolean v1, p0, LX/8CU;->enableHttpPriorityForPrefetch:Z

    iput-boolean v1, p0, LX/8CU;->enableHttpPriorityForStreaming:Z

    iput-boolean v1, p0, LX/8CU;->useHttpPriorityIncrementalForStreaming:Z

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/8CU;->useHttpPriorityIncrementalForPrefetch:Z

    iput-boolean v0, p0, LX/8CU;->useHttpPriorityIncrementalForLongBufferedStreaming:Z

    iput-boolean v1, p0, LX/8CU;->useHttpPriorityWarmupForLongBufferedStreaming:Z

    iput-boolean v1, p0, LX/8CU;->useNetworkAwareHttpPriorityIncrementalForStreaming:Z

    iput-boolean v1, p0, LX/8CU;->useLowPriorityForSecondPhasePrefetch:Z

    iput v1, p0, LX/8CU;->bufferedDurationBasedHttpPriorityUpperBoundMs:I

    iput v1, p0, LX/8CU;->bufferedDurationBasedHttpPriorityLowerBoundMs:I

    const/high16 v0, -0x40800000    # -1.0f

    iput v0, p0, LX/8CU;->watchTimeThresholdToDisableSecondPhasePrefetchSeconds:F

    iput-boolean v1, p0, LX/8CU;->changePriorityForPrefetchRequestOnPlayerStart:Z

    iput-boolean v1, p0, LX/8CU;->useLowerHttpPriorityForUnimportantPrefetch:Z

    iput-boolean v1, p0, LX/8CU;->useLowerHttpPriorityForAllPrefetch:Z

    iput-boolean v1, p0, LX/8CU;->useOutputSurfaceWorkaround:Z

    iput-boolean v1, p0, LX/8CU;->enableBufferAwareJumpSeek:Z

    iput v1, p0, LX/8CU;->jumpSeekPosLeftoverBufferDurationMs:I

    iput v1, p0, LX/8CU;->jumpSeekReductionFactorPct:I

    iput-boolean v1, p0, LX/8CU;->enableBackwardJumpSeekKeyframeSync:Z

    iput v1, p0, LX/8CU;->seekParameterOptionIndex:I

    iput-boolean v1, p0, LX/8CU;->skipAV1PreviousKeyFrameSeek:Z

    iput-boolean v1, p0, LX/8CU;->enableCacheLookUp:Z

    iput-boolean v1, p0, LX/8CU;->usePerVideoLookupToCheckCache:Z

    iput-boolean v1, p0, LX/8CU;->useIsCachedSkipInit:Z

    iput-boolean v1, p0, LX/8CU;->releaseHeroManagerWhenLowMemInBg:Z

    iput-boolean v1, p0, LX/8CU;->useAdAwareLoadControl:Z

    const v0, 0x3e99999a    # 0.3f

    iput v0, p0, LX/8CU;->huddleLatencyMaxSpeedDelta:F

    iput-boolean v1, p0, LX/8CU;->enablePIDForHuddle:Z

    iput-boolean v1, p0, LX/8CU;->forceStereoToMonoConversion:Z

    iput-boolean v1, p0, LX/8CU;->enableQuickDashPlayback:Z

    iput-boolean v1, p0, LX/8CU;->enableClockSync:Z

    iput-boolean v1, p0, LX/8CU;->enableStreamLatencyToggleOverride:Z

    iput v1, p0, LX/8CU;->streamLatencyToggleStateOverride:I

    const/16 v0, 0xbb8

    iput v0, p0, LX/8CU;->streamLatencyTogglePIDDesiredBufferMs:I

    const v0, 0x1d4c0

    iput v0, p0, LX/8CU;->streamLatencyTogglePIDIntegralBoundMs:I

    const v0, 0x3e99999a    # 0.3f

    iput v0, p0, LX/8CU;->streamLatencyToggleMaxSpeedDelta:F

    const/high16 v0, 0x40000000    # 2.0f

    iput v0, p0, LX/8CU;->streamLatencyToggleSpeedUpBandwidthMultiplier:F

    iput-boolean v1, p0, LX/8CU;->includePlaybackSessionIdHeader:Z

    iput-boolean v1, p0, LX/8CU;->enableE2ECDNTracing:Z

    iput-boolean v1, p0, LX/8CU;->enablePredictedUrlTracing:Z

    iput-object v2, p0, LX/8CU;->broadcasterIdAllowlist:Ljava/lang/String;

    iput-object v2, p0, LX/8CU;->playerOriginPausedLoadingBlackList:Ljava/lang/String;

    iget-object v0, p1, LX/7OH;->A0Y:Ljava/util/Set;

    iput-object v0, p0, LX/8CU;->pausedLoadingTriggerTypes:Ljava/util/Set;

    iget-object v0, p1, LX/7OH;->A0X:Ljava/util/Set;

    iput-object v0, p0, LX/8CU;->originAllowlistForAlternateCodec:Ljava/util/Set;

    iget-object v0, p1, LX/7OH;->A0c:Ljava/util/Set;

    iput-object v0, p0, LX/8CU;->wakelockOriginLists:Ljava/util/Set;

    iput-boolean v1, p0, LX/8CU;->enableExcessiveNumUriRedirectLogging:Z

    iput v1, p0, LX/8CU;->excessiveUriRedirectLoggingLimit:I

    iput-boolean v1, p0, LX/8CU;->enableVodPausedLoading:Z

    iput v1, p0, LX/8CU;->maxBufferToDownloadInPausedLoadingMs:I

    iput v1, p0, LX/8CU;->maxTimeAllowedSpentInPausedLoadingMs:I

    iput-boolean v1, p0, LX/8CU;->enableLastPlaybackSpeedCacheUpdate:Z

    iput-boolean v1, p0, LX/8CU;->enableIsTextAdaptationSetNotFoundLogging:Z

    iput-boolean v1, p0, LX/8CU;->enableOffloadInitHeroService:Z

    iput-boolean v1, p0, LX/8CU;->enableBackgroundServicePlayerReuse:Z

    iput-boolean v1, p0, LX/8CU;->useMinIntentBasedWatermarkBeforePlay:Z

    iput-boolean v1, p0, LX/8CU;->enableMediaSessionControls:Z

    iput-boolean v1, p0, LX/8CU;->enableRequestAnalyticsTagsHeaderLogging:Z

    iput-boolean v1, p0, LX/8CU;->disableTextRendererOn404LoadError:Z

    iput-boolean v1, p0, LX/8CU;->useFallbackLogging:Z

    iput-boolean v1, p0, LX/8CU;->disableTextRendererOn404InitSegmentLoadError:Z

    iput-boolean v1, p0, LX/8CU;->disableTextRendererOn500LoadError:Z

    iput-boolean v1, p0, LX/8CU;->disableTextRendererOn500InitSegmentLoadError:Z

    iput-boolean v1, p0, LX/8CU;->enableVideoPlayerServerSideBweAnnotations:Z

    iput-boolean v1, p0, LX/8CU;->enableUnexpectedExoExceptionLogging:Z

    iput-boolean v1, p0, LX/8CU;->enableEmsgTrackForAll:Z

    iput-boolean v1, p0, LX/8CU;->enableInstreamAdsEmsgLog:Z

    iput v1, p0, LX/8CU;->audioStallCountThresholdMs:I

    iput-boolean v1, p0, LX/8CU;->enableVideoPositionLoggingInCompleteEvent:Z

    iput-boolean v1, p0, LX/8CU;->surfaceMPDFailoverImmediately:Z

    iput-boolean v1, p0, LX/8CU;->disableTextTrackOnMissingTextTrack:Z

    iput-boolean v1, p0, LX/8CU;->enableTextTrackWithKnownLanguage:Z

    iput v1, p0, LX/8CU;->numDashChunkMemoryCacheSampleStreams:I

    iput-boolean v1, p0, LX/8CU;->disableTextEraLoggingOnLoadRetry:Z

    iget-object v0, p1, LX/7OH;->A0Q:LX/8C7;

    iput-object v0, p0, LX/8CU;->tslogSettings:LX/8C7;

    iput-boolean v1, p0, LX/8CU;->dontRetry403OnExpiredUrl:Z

    iput-boolean v1, p0, LX/8CU;->useFullscreenTransitionPrediction:Z

    const-wide/16 v0, 0x7d0

    iput-wide v0, p0, LX/8CU;->fullscreenPredictionRequestTimeoutMs:J

    const/4 v0, -0x1

    iput v0, p0, LX/8CU;->maxAllowed503RetryCount:I

    const-wide/16 v0, 0x0

    iput-wide v0, p0, LX/8CU;->advanceSegmentOnNetworkErrors:J

    iput-wide v0, p0, LX/8CU;->maxSegmentsToAdvance:J

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->enableExplicitTextDataSourceCreation:Z

    iput-boolean v0, p0, LX/8CU;->disableLiveCaptioningOnPlayerInit:Z

    iput-boolean v0, p0, LX/8CU;->enableVrlQplLoggingEvents:Z

    iput-boolean v0, p0, LX/8CU;->reduceMemoryDataSinkMemorySpike:Z

    iput-boolean v0, p0, LX/8CU;->useExoPlayerBuilder:Z

    iput-boolean v0, p0, LX/8CU;->exoPlayerUpgrade218verifyApplicationThread:Z

    iput-boolean v0, p0, LX/8CU;->enable416Logging:Z

    iput-boolean v0, p0, LX/8CU;->enableVodContentLengthLogging:Z

    iput-boolean v0, p0, LX/8CU;->enableServerSideForwardTracing:Z

    iput-boolean v0, p0, LX/8CU;->enableMixedCodecManifestSupport:Z

    iput-boolean v0, p0, LX/8CU;->respectAbrForUll:Z

    iput-boolean v0, p0, LX/8CU;->respectAbrIndexForUll:Z

    iput-boolean v0, p0, LX/8CU;->disableUllBasedOnHoldout:Z

    iput-boolean v0, p0, LX/8CU;->enableWifiLockManager:Z

    iput-boolean v0, p0, LX/8CU;->enableClearStallOnBroadcastEnd:Z

    iput-boolean v0, p0, LX/8CU;->enableSecondaryChannelLoggingForLite:Z

    iput-boolean v0, p0, LX/8CU;->enableDav1dAsMediaCodecAdapter:Z

    iput-boolean v0, p0, LX/8CU;->enableDav1dOpenGLRendering:Z

    iput v0, p0, LX/8CU;->secondaryChannelLoggingMaxNumOfFramesInOneJson:I

    iput v0, p0, LX/8CU;->secondaryChannelLoggingMaxDisplayedFramesStringSize:I

    iput v0, p0, LX/8CU;->secondaryChannelLoggingSamplingFactor:I

    iput-boolean v0, p0, LX/8CU;->surfaceControlForceVideoSizeUpdate:Z

    iput-boolean v0, p0, LX/8CU;->forceAdjustSurfaceOnMainThread:Z

    iput-boolean v0, p0, LX/8CU;->disableVideoTrackForInVisibleVDD:Z

    iput-boolean v0, p0, LX/8CU;->shouldDisableAV1VideoTrackOnlyforVDD:Z

    iput-boolean v0, p0, LX/8CU;->useInterruptedIoException:Z

    iput-boolean v0, p0, LX/8CU;->enableMixeCodecManifestLogging:Z

    iput-boolean v0, p0, LX/8CU;->enableMixeCodecManifestVideoCodecSwitchedLogging:Z

    iput-boolean v0, p0, LX/8CU;->enablePCMBufferListener:Z

    iput-boolean v0, p0, LX/8CU;->enableLoggingEmptyOrNullVideoId:Z

    iput-boolean v0, p0, LX/8CU;->enableDav1dOpenGLIncorrectSurfaceSizeFix:Z

    iput-boolean v0, p0, LX/8CU;->useBufferedCacheDataSink:Z

    iput-boolean v0, p0, LX/8CU;->useHandlerThreadPool:Z

    iget-boolean v0, p1, LX/7OH;->A0n:Z

    iput-boolean v0, p0, LX/8CU;->useMainThreadForHeroPlayer:Z

    const/4 v0, 0x4

    iput v0, p0, LX/8CU;->handlerThreadPoolSize:I

    const/4 v0, 0x0

    iput v0, p0, LX/8CU;->bufferedCacheDataSinkSize:I

    iput-boolean v0, p0, LX/8CU;->enableAV1SRShader:Z

    const/16 v0, 0x3e8

    iput v0, p0, LX/8CU;->maxWidthForAV1SRShader:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->enableSaturation:Z

    const/high16 v0, 0x3f800000    # 1.0f

    iput v0, p0, LX/8CU;->saturationFactor:F

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->enableAdditionalDecoderInitFailureMessage:Z

    iput-boolean v0, p0, LX/8CU;->enableFixForOnPreparingCallback:Z

    iput-boolean v0, p0, LX/8CU;->enableOpenGLSurfaceSizeUpdateFix:Z

    iput-object v2, p0, LX/8CU;->prefetchSubOriginBlockList:Ljava/lang/String;

    iput-boolean v0, p0, LX/8CU;->enforceSizeLimitOnSecondPhasePrefetch:Z

    iput-boolean v0, p0, LX/8CU;->attachGrootPlayerListenerWhenUsingSurfaceControl:Z

    iput-boolean v0, p0, LX/8CU;->resizeAndRepositionGrootSurfaceControl:Z

    iput-boolean v0, p0, LX/8CU;->preventAdjustWhenSurfaceNotValid:Z

    iput v0, p0, LX/8CU;->forceManifestFilteringMode:I

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/8CU;->enableDav1dOpenGLRenderingHandleAspectRatio:Z

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->enableMpdFilteringUtils:Z

    iput-boolean v0, p0, LX/8CU;->enableTransferListenerCallbackPerfFix:Z

    iput-boolean v0, p0, LX/8CU;->enableDynamicPrefetchCacheFileSize:Z

    iput-boolean v0, p0, LX/8CU;->enableDynamicPrefetchCacheFileSizePrefetchOnly:Z

    const-wide/16 v0, 0x0

    iput-wide v0, p0, LX/8CU;->minCacheFileSizeForDynamicChunkingInBytes:J

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/8CU;->enableDashManifestPool:Z

    iput v0, p0, LX/8CU;->dashManifestPoolSize:I

    iput-boolean v0, p0, LX/8CU;->disablePoolingForDav1dMediaCodec:Z

    iput-boolean v0, p0, LX/8CU;->useBackgroundHandlerForHeroLiveManager:Z

    iput-boolean v0, p0, LX/8CU;->useAllSettingsToSupportLowerLatency:Z

    iput-boolean v0, p0, LX/8CU;->combineInitFirstSegment:Z

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/8CU;->fixNullCacheSpan:Z

    const/4 v1, 0x0

    iput-boolean v1, p0, LX/8CU;->enableAudioTrackRetry:Z

    iput v1, p0, LX/8CU;->playbackAboutToFinishCallbackTriggeringRemainingDuration:I

    iget-boolean v0, p1, LX/7OH;->A0j:Z

    iput-boolean v0, p0, LX/8CU;->shouldAddDefaultMP4Extractor:Z

    iget-boolean v0, p1, LX/7OH;->A0i:Z

    iput-boolean v0, p0, LX/8CU;->quitHandlerSafely:Z

    iget-boolean v0, p1, LX/7OH;->A0k:Z

    iput-boolean v0, p0, LX/8CU;->shouldCleanupHeroManagerThread:Z

    iput-boolean v1, p0, LX/8CU;->enableCodecHistoryOverlayField:Z

    iput-boolean v1, p0, LX/8CU;->appendReconfigurationDataForDrmContentFix:Z

    iget v0, p1, LX/7OH;->A0C:I

    iput v0, p0, LX/8CU;->sdkVersionToUseDefaultLoadControl:I

    iget v0, p1, LX/7OH;->A0B:I

    iput v0, p0, LX/8CU;->sdkVersionToUseConservativeLoadControl:I

    iget v0, p1, LX/7OH;->A08:I

    iput v0, p0, LX/8CU;->sdKVersionToUseCustomizedBuffering:I

    iget v0, p1, LX/7OH;->A09:I

    iput v0, p0, LX/8CU;->sdKVersionToUseTargetBufferOverwrite:I

    iget v0, p1, LX/7OH;->A06:I

    iput v0, p0, LX/8CU;->minCustomizedWABufferMs:I

    iget v0, p1, LX/7OH;->A0E:I

    iput v0, p0, LX/8CU;->targetBytesForOverwrite:I

    iget v0, p1, LX/7OH;->A05:I

    iput v0, p0, LX/8CU;->maxCustomizedWABufferMs:I

    iget v0, p1, LX/7OH;->A00:I

    iput v0, p0, LX/8CU;->customizedWABufferForPlaybackMs:I

    iget v0, p1, LX/7OH;->A02:I

    iput v0, p0, LX/8CU;->customizedWARebufferMs:I

    iget v0, p1, LX/7OH;->A01:I

    iput v0, p0, LX/8CU;->customizedWAIndividualAllocationSize:I

    iget-boolean v0, p1, LX/7OH;->A0g:Z

    iput-boolean v0, p0, LX/8CU;->enableHeroPlayerMaxLoopCount:Z

    iget-boolean v0, p1, LX/7OH;->A0d:Z

    iput-boolean v0, p0, LX/8CU;->allowRequestForSoftwareDecoder:Z

    iget-boolean v0, p1, LX/7OH;->A0l:Z

    iput-boolean v0, p0, LX/8CU;->useDefaultTrackSelector:Z

    iget v0, p1, LX/7OH;->A0A:I

    iput v0, p0, LX/8CU;->sdkVersionToBypassHeroStateRefresh:I

    iget-boolean v0, p1, LX/7OH;->A0o:Z

    iput-boolean v0, p0, LX/8CU;->useWAPlayerPoolLoadControl:Z

    return-void
.end method
